import { Router } from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import lessonRoutes from './lesson.routes.js';
import vocabRoutes from './vocab.routes.js';
import srsRoutes from './srs.routes.js';
import favoriteRoutes from './favorite.routes.js';
import listRoutes from './list.routes.js';
import aiRoutes from './ai.routes.js';
import practiceRoutes from './practice.routes.js';
import utilityRoutes from './utility.routes.js';
import audioRoutes from './audio.routes.js';
import adminRoutes from './admin.routes.js';
import friendRoutes from './friend.routes.js';
import leaderboardRoutes from './leaderboard.routes.js';
import docsRoutes from './docs.routes.js';
import placementRoutes from './placement.routes.js';
import { healthCheck } from '../controllers/health.controller.js';

const router = Router();

router.get('/health', healthCheck);
router.use('/docs', docsRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/lessons', lessonRoutes);
router.use('/vocab', vocabRoutes);
router.use('/srs', srsRoutes);
router.use('/favorites', favoriteRoutes);
router.use('/lists', listRoutes);
router.use('/ai-tutor', aiRoutes);
router.use('/practice', practiceRoutes);
router.use('/audio', audioRoutes);
router.use('/admin', adminRoutes);
router.use('/friends', friendRoutes);
router.use('/leaderboard', leaderboardRoutes);
router.use('/placement', placementRoutes);
router.use('/', utilityRoutes);

export default router;
