// Sino-Vietnamese (âm Hán-Việt) readings for common Han characters.
//
// This is a curated, high-frequency subset (covering roughly HSK 1–3 plus common
// characters). Each entry is the primary Sino-Vietnamese reading for the character.
// Word-level readings are composed by joining the per-character readings, which is
// how Vietnamese learners conventionally read a Chinese compound.
//
// To extend coverage, add characters below — keep readings lowercase and accurate.
export const HAN_VIET_MAP = {
  一: 'nhất', 丁: 'đinh', 七: 'thất', 万: 'vạn', 三: 'tam', 上: 'thượng', 下: 'hạ',
  不: 'bất', 与: 'dữ', 丑: 'sửu', 专: 'chuyên', 且: 'thả', 世: 'thế', 业: 'nghiệp',
  东: 'đông', 丝: 'ti', 两: 'lưỡng', 严: 'nghiêm', 个: 'cá', 中: 'trung', 丰: 'phong',
  串: 'xuyến', 临: 'lâm', 丸: 'hoàn', 主: 'chủ', 丽: 'lệ', 举: 'cử', 乃: 'nãi',
  久: 'cửu', 么: 'ma', 义: 'nghĩa', 之: 'chi', 乌: 'ô', 乎: 'hồ', 乐: 'lạc',
  乔: 'kiều', 乖: 'quai', 乘: 'thừa', 乙: 'ất', 九: 'cửu', 也: 'dã', 习: 'tập',
  乡: 'hương', 书: 'thư', 买: 'mãi', 乱: 'loạn', 了: 'liễu', 争: 'tranh', 事: 'sự',
  二: 'nhị', 于: 'vu', 亏: 'khuy', 云: 'vân', 互: 'hỗ', 五: 'ngũ', 井: 'tỉnh',
  亚: 'á', 些: 'ta', 亡: 'vong', 交: 'giao', 亦: 'diệc', 产: 'sản', 亨: 'hanh',
  京: 'kinh', 亭: 'đình', 亮: 'lượng', 亲: 'thân', 人: 'nhân', 亿: 'ức', 什: 'thập',
  仁: 'nhân', 仅: 'cận', 今: 'kim', 介: 'giới', 仍: 'nhưng', 从: 'tùng', 仓: 'thương',
  仔: 'tử', 他: 'tha', 仗: 'trượng', 付: 'phó', 仙: 'tiên', 代: 'đại', 令: 'lệnh',
  以: 'dĩ', 仪: 'nghi', 们: 'môn', 价: 'giá', 任: 'nhậm', 份: 'phần', 仿: 'phảng',
  企: 'xí', 伟: 'vĩ', 传: 'truyền', 伤: 'thương', 伦: 'luân', 伯: 'bá', 估: 'cổ',
  伴: 'bạn', 伸: 'thân', 似: 'tự', 但: 'đãn', 位: 'vị', 低: 'đê', 住: 'trú',
  体: 'thể', 何: 'hà', 余: 'dư', 佛: 'phật', 作: 'tác', 你: 'nễ', 佩: 'bội',
  佳: 'giai', 使: 'sử', 例: 'lệ', 供: 'cung', 依: 'y', 侠: 'hiệp',
  侣: 'lữ', 侦: 'trinh', 侧: 'trắc', 侨: 'kiều', 侮: 'vũ', 便: 'tiện', 系: 'hệ',
  俗: 'tục', 保: 'bảo', 信: 'tín', 修: 'tu', 俩: 'lưỡng', 倍: 'bội', 候: 'hậu',
  倒: 'đảo', 借: 'tá', 值: 'trị', 倾: 'khuynh', 假: 'giả', 停: 'đình', 健: 'kiện', 做: 'tố', 偶: 'ngẫu', 偷: 'thâu',
  傅: 'phó', 储: 'trữ', 催: 'thôi', 傲: 'ngạo', 像: 'tượng', 僧: 'tăng', 儿: 'nhi',
  允: 'duẫn', 元: 'nguyên', 兄: 'huynh', 充: 'sung', 兆: 'triệu', 先: 'tiên',
  光: 'quang', 克: 'khắc', 免: 'miễn', 兔: 'thố', 党: 'đảng', 入: 'nhập',
  全: 'toàn', 八: 'bát', 公: 'công', 六: 'lục', 兰: 'lan', 共: 'cộng', 关: 'quan',
  兴: 'hưng', 兵: 'binh', 其: 'kỳ', 具: 'cụ', 典: 'điển', 养: 'dưỡng', 兽: 'thú',
  内: 'nội', 冈: 'cương', 册: 'sách', 再: 'tái', 冒: 'mạo', 军: 'quân', 农: 'nông',
  冠: 'quan', 冬: 'đông', 冰: 'băng', 冷: 'lãnh', 准: 'chuẩn', 凉: 'lương',
  减: 'giảm', 凡: 'phàm', 凤: 'phượng', 凭: 'bằng', 凶: 'hung', 出: 'xuất',
  击: 'kích', 函: 'hàm', 刀: 'đao', 分: 'phân', 切: 'thiết', 刊: 'san', 刑: 'hình',
  划: 'hoạch', 列: 'liệt', 则: 'tắc', 创: 'sáng', 初: 'sơ', 判: 'phán', 别: 'biệt',
  利: 'lợi', 到: 'đáo', 制: 'chế', 刷: 'loát', 刺: 'thứ', 刻: 'khắc', 剑: 'kiếm',
  剧: 'kịch', 剩: 'thặng', 副: 'phó', 割: 'cát', 力: 'lực', 办: 'biện', 功: 'công',
  加: 'gia', 务: 'vụ', 动: 'động', 助: 'trợ', 努: 'nỗ', 劳: 'lao', 势: 'thế',
  勇: 'dũng', 勉: 'miễn', 勒: 'lặc', 勤: 'cần', 勾: 'câu', 包: 'bao', 化: 'hóa',
  北: 'bắc', 匙: 'chủy', 匹: 'thất', 区: 'khu', 医: 'y', 十: 'thập', 千: 'thiên',
  升: 'thăng', 午: 'ngọ', 半: 'bán', 华: 'hoa', 协: 'hiệp', 单: 'đơn', 卖: 'mại',
  南: 'nam', 博: 'bác', 卜: 'bốc', 占: 'chiếm', 卡: 'ca', 卢: 'lư', 卫: 'vệ',
  印: 'ấn', 危: 'nguy', 即: 'tức', 却: 'khước', 卷: 'quyển', 厂: 'xưởng',
  厅: 'sảnh', 历: 'lịch', 厉: 'lệ', 压: 'áp', 厌: 'yếm', 厚: 'hậu', 原: 'nguyên',
  厨: 'trù', 去: 'khứ', 县: 'huyện', 参: 'tham', 又: 'hựu', 叉: 'xoa', 及: 'cập',
  友: 'hữu', 双: 'song', 反: 'phản', 发: 'phát', 叔: 'thúc', 取: 'thủ', 受: 'thụ',
  变: 'biến', 叙: 'tự', 口: 'khẩu', 古: 'cổ', 句: 'cú', 另: 'lánh', 只: 'chỉ',
  叫: 'khiếu', 召: 'triệu', 可: 'khả', 台: 'đài', 史: 'sử', 右: 'hữu', 叶: 'diệp',
  号: 'hào', 司: 'ti', 各: 'các', 合: 'hợp', 吉: 'cát', 吊: 'điếu', 同: 'đồng',
  名: 'danh', 后: 'hậu', 吐: 'thổ', 向: 'hướng', 吓: 'hách', 吗: 'ma', 君: 'quân',
  吝: 'lận', 吧: 'ba', 吨: 'đốn', 听: 'thính', 吩: 'phân', 吮: 'duyện', 启: 'khải',
  吵: 'sảo', 吸: 'hấp', 吹: 'xuy', 吻: 'vẫn', 吼: 'hống', 吾: 'ngô', 呀: 'nha',
  呆: 'ngai', 告: 'cáo', 呕: 'ẩu', 员: 'viên', 呛: 'sang', 呢: 'ni', 周: 'chu',
  味: 'vị', 呵: 'ha', 呼: 'hô', 命: 'mệnh', 咖: 'ca', 咨: 'tư', 咬: 'giảo',
  咳: 'khái', 咸: 'hàm', 品: 'phẩm', 哀: 'ai', 响: 'hưởng', 哈: 'cáp', 哎: 'ai',
  哥: 'ca', 哦: 'ồ', 哭: 'khốc', 哲: 'triết', 唉: 'ai', 唐: 'đường', 售: 'thụ',
  唯: 'duy', 唱: 'xướng', 商: 'thương', 啊: 'a', 啡: 'phi', 啤: 'bia', 啦: 'la',
  喀: 'khách', 善: 'thiện', 喇: 'lạt', 喉: 'hầu', 喊: 'hảm', 喔: 'ô', 喘: 'suyễn',
  喜: 'hỉ', 喝: 'hát', 喧: 'huyên', 喷: 'phún', 喻: 'dụ', 嗓: 'tảng', 嘛: 'ma',
  嘴: 'chủy', 器: 'khí', 四: 'tứ', 回: 'hồi', 因: 'nhân', 团: 'đoàn', 园: 'viên',
  困: 'khốn', 围: 'vi', 固: 'cố', 国: 'quốc', 图: 'đồ', 圆: 'viên', 圈: 'quyển',
  土: 'thổ', 圣: 'thánh', 在: 'tại', 地: 'địa', 场: 'trường', 圾: 'ngập', 址: 'chỉ',
  坏: 'hoại', 坐: 'tọa', 块: 'khối', 坚: 'kiên', 坛: 'đàn', 坟: 'phần', 坡: 'pha',
  坦: 'thản', 垂: 'thùy', 垃: 'lạp', 型: 'hình', 埃: 'ai', 城: 'thành', 域: 'vực',
  培: 'bồi', 基: 'cơ', 堂: 'đường', 堆: 'đôi', 堵: 'đổ', 塑: 'tố', 塔: 'tháp',
  塞: 'tắc', 填: 'điền', 境: 'cảnh', 增: 'tăng', 墨: 'mặc', 壁: 'bích', 士: 'sĩ',
  壮: 'tráng', 声: 'thanh', 壳: 'xác', 处: 'xử', 备: 'bị', 复: 'phục', 夏: 'hạ',
  夕: 'tịch', 外: 'ngoại', 多: 'đa', 夜: 'dạ', 够: 'cấu', 大: 'đại', 天: 'thiên',
  太: 'thái', 夫: 'phu', 央: 'ương', 失: 'thất', 头: 'đầu', 夷: 'di', 夸: 'khoa',
  夹: 'giáp', 奇: 'kỳ', 奈: 'nại', 奉: 'phụng', 奋: 'phấn', 奏: 'tấu', 契: 'khế',
  奔: 'bôn', 奖: 'thưởng', 套: 'sáo', 奥: 'áo', 女: 'nữ', 奴: 'nô', 奶: 'nãi',
  好: 'hảo', 如: 'như', 妈: 'ma', 妙: 'diệu', 妆: 'trang', 妇: 'phụ',
  妥: 'thỏa', 妹: 'muội', 妻: 'thê', 姐: 'tỷ', 姑: 'cô', 姓: 'tính',
  委: 'ủy', 姿: 'tư', 威: 'uy', 娃: 'oa', 娘: 'nương', 婆: 'bà', 婚: 'hôn',
  媒: 'môi', 嫁: 'giá', 嫌: 'hiềm', 子: 'tử', 孔: 'khổng', 字: 'tự', 存: 'tồn',
  孙: 'tôn', 孝: 'hiếu', 孤: 'cô', 学: 'học', 孩: 'hài', 孵: 'phu', 宁: 'ninh',
  它: 'tha', 宅: 'trạch', 宇: 'vũ', 守: 'thủ', 安: 'an', 完: 'hoàn', 宏: 'hoành',
  宗: 'tông', 官: 'quan', 定: 'định', 宜: 'nghi', 宝: 'bảo', 实: 'thực', 宠: 'sủng',
  审: 'thẩm', 客: 'khách', 宣: 'tuyên', 室: 'thất', 宪: 'hiến', 害: 'hại',
  宴: 'yến', 家: 'gia', 容: 'dung', 宽: 'khoan', 宾: 'tân', 宿: 'túc', 寂: 'tịch',
  寄: 'ký', 密: 'mật', 富: 'phú', 寒: 'hàn', 寝: 'tẩm', 察: 'sát', 寸: 'thốn',
  对: 'đối', 寺: 'tự', 寻: 'tầm', 导: 'đạo', 封: 'phong', 射: 'xạ', 将: 'tương',
  尊: 'tôn', 小: 'tiểu', 少: 'thiểu', 尔: 'nhĩ', 尖: 'tiêm', 尚: 'thượng',
  尝: 'thường', 尤: 'vưu', 就: 'tựu', 尺: 'xích', 尼: 'ni', 尽: 'tận', 尾: 'vĩ',
  局: 'cục', 屈: 'khuất', 居: 'cư', 届: 'giới', 屋: 'ốc', 屏: 'bình', 屑: 'tiết',
  展: 'triển', 属: 'thuộc', 山: 'sơn', 岁: 'tuế', 岛: 'đảo', 岸: 'ngạn',
  峰: 'phong', 崇: 'sùng', 川: 'xuyên', 州: 'châu', 巡: 'tuần', 工: 'công',
  左: 'tả', 巧: 'xảo', 巨: 'cự', 差: 'sai', 己: 'kỷ', 已: 'dĩ', 巴: 'ba',
  巷: 'hạng', 币: 'tệ', 市: 'thị', 布: 'bố', 帅: 'súy', 师: 'sư', 希: 'hy',
  帐: 'trướng', 帘: 'liêm', 帜: 'xí', 帝: 'đế', 带: 'đái', 席: 'tịch', 帮: 'bang',
  常: 'thường', 帽: 'mạo', 幅: 'phúc', 干: 'can', 平: 'bình', 年: 'niên',
  并: 'tịnh', 幸: 'hạnh', 幻: 'huyễn', 幼: 'ấu', 广: 'quảng', 庄: 'trang',
  庆: 'khánh', 床: 'sàng', 序: 'tự', 库: 'khố', 应: 'ứng', 底: 'để', 店: 'điếm',
  庙: 'miếu', 府: 'phủ', 度: 'độ', 座: 'tọa', 庭: 'đình', 康: 'khang', 廉: 'liêm',
  延: 'diên', 建: 'kiến', 开: 'khai', 异: 'dị', 弃: 'khí', 弄: 'lộng', 式: 'thức',
  引: 'dẫn', 弟: 'đệ', 张: 'trương', 弥: 'di', 弦: 'huyền', 弯: 'loan', 弱: 'nhược',
  强: 'cường', 归: 'quy', 当: 'đương', 录: 'lục', 形: 'hình', 彩: 'thái',
  影: 'ảnh', 役: 'dịch', 彻: 'triệt', 往: 'vãng', 征: 'chinh', 径: 'kính',
  待: 'đãi', 很: 'ngận', 律: 'luật', 徐: 'từ', 徒: 'đồ', 得: 'đắc',
  循: 'tuần', 微: 'vi', 德: 'đức', 心: 'tâm', 必: 'tất', 忆: 'ức', 忌: 'kỵ',
  忍: 'nhẫn', 志: 'chí', 忘: 'vong', 忙: 'mang', 忠: 'trung', 快: 'khoái',
  念: 'niệm', 忽: 'hốt', 怀: 'hoài', 态: 'thái', 怒: 'nộ', 怕: 'phạ', 怖: 'bố',
  思: 'tư', 急: 'cấp', 性: 'tính', 怨: 'oán', 怪: 'quái', 总: 'tổng', 恋: 'luyến',
  恐: 'khủng', 恒: 'hằng', 恨: 'hận', 恩: 'ân', 恰: 'kháp', 恳: 'khẩn',
  息: 'tức', 恼: 'não', 悉: 'tất', 悔: 'hối', 悟: 'ngộ', 患: 'hoạn', 悬: 'huyền',
  悲: 'bi', 情: 'tình', 惑: 'hoặc', 惜: 'tích', 惯: 'quán', 想: 'tưởng',
  惹: 'nhạ', 愁: 'sầu', 愈: 'dũ', 意: 'ý', 愚: 'ngu', 感: 'cảm', 愧: 'quý',
  慌: 'hoảng', 慎: 'thận', 慕: 'mộ', 慢: 'mạn', 慧: 'tuệ', 慰: 'úy', 憾: 'hám',
  懂: 'đổng', 懒: 'lãn', 戈: 'qua', 戏: 'hí', 成: 'thành', 我: 'ngã', 戒: 'giới',
  或: 'hoặc', 战: 'chiến', 截: 'tiệt', 戴: 'đái', 户: 'hộ', 房: 'phòng', 所: 'sở',
  扁: 'biển', 手: 'thủ', 才: 'tài', 扎: 'trát', 打: 'đả', 托: 'thác', 扣: 'khấu',
  执: 'chấp', 扩: 'khoách', 扫: 'tảo', 扬: 'dương', 扮: 'ban', 扰: 'nhiễu',
  批: 'phê', 找: 'trảo', 承: 'thừa', 技: 'kỹ', 抄: 'sao', 把: 'bả', 抑: 'ức',
  投: 'đầu', 抗: 'kháng', 折: 'chiết', 抚: 'phủ', 抛: 'phao', 抢: 'thưởng',
  护: 'hộ', 报: 'báo', 抱: 'bão', 抵: 'để', 抹: 'mạt', 押: 'áp', 抽: 'trừu',
  担: 'đảm', 拆: 'sách', 拉: 'lạp', 拍: 'phách', 拒: 'cự', 拔: 'bạt', 拖: 'tha',
  招: 'chiêu', 拜: 'bái', 括: 'quát', 拳: 'quyền', 拾: 'thập', 拿: 'nã',
  持: 'trì', 指: 'chỉ', 按: 'án', 挑: 'khiêu', 挖: 'oạt', 挥: 'huy', 振: 'chấn',
  挺: 'đĩnh', 捐: 'quyên', 捕: 'bộ', 损: 'tổn', 换: 'hoán', 据: 'cứ', 捷: 'tiệp',
  授: 'thụ', 掉: 'điệu', 掌: 'chưởng', 排: 'bài', 探: 'thám', 接: 'tiếp',
  控: 'khống', 推: 'thôi', 措: 'thố', 描: 'miêu', 提: 'đề', 插: 'sáp', 握: 'ác',
  援: 'viện', 搜: 'sưu', 搬: 'ban', 摄: 'nhiếp', 摆: 'bãi', 摇: 'diêu', 摊: 'than',
  摩: 'ma', 摸: 'mô', 撑: 'sanh', 撞: 'chàng', 播: 'bá', 操: 'thao', 擦: 'sát',
  支: 'chi', 收: 'thu', 改: 'cải', 攻: 'công', 放: 'phóng', 政: 'chính', 故: 'cố',
  效: 'hiệu', 敌: 'địch', 敏: 'mẫn', 救: 'cứu', 教: 'giáo', 敢: 'cảm', 散: 'tán',
  敬: 'kính', 数: 'số', 整: 'chỉnh', 文: 'văn', 斗: 'đấu', 料: 'liệu', 斜: 'tà',
  斤: 'cân', 斥: 'xích', 断: 'đoạn', 斯: 'tư', 新: 'tân', 方: 'phương', 施: 'thi',
  旁: 'bàng', 旅: 'lữ', 旋: 'toàn', 族: 'tộc', 旗: 'kỳ', 无: 'vô', 既: 'ký',
  日: 'nhật', 旧: 'cựu', 旦: 'đán', 早: 'tảo', 旬: 'tuần', 旭: 'húc', 时: 'thời',
  旺: 'vượng', 昂: 'ngang', 昆: 'côn', 明: 'minh', 昏: 'hôn', 易: 'dịch',
  星: 'tinh', 映: 'ánh', 春: 'xuân', 昨: 'tạc', 是: 'thị', 显: 'hiển', 晃: 'hoảng',
  晒: 'sái', 晚: 'vãn', 晨: 'thần', 普: 'phổ', 景: 'cảnh', 晴: 'tình', 晶: 'tinh',
  智: 'trí', 暂: 'tạm', 暗: 'ám', 暖: 'noãn', 暴: 'bạo', 曲: 'khúc', 更: 'canh',
  曾: 'tằng', 替: 'thế', 最: 'tối', 月: 'nguyệt', 有: 'hữu', 朋: 'bằng',
  服: 'phục', 望: 'vọng', 朝: 'triều', 期: 'kỳ', 木: 'mộc', 未: 'vị', 末: 'mạt',
  本: 'bản', 术: 'thuật', 朴: 'phác', 机: 'cơ', 杀: 'sát', 杂: 'tạp', 权: 'quyền',
  杆: 'can', 李: 'lý', 材: 'tài', 村: 'thôn', 杜: 'đỗ', 束: 'thúc', 条: 'điều',
  来: 'lai', 杨: 'dương', 杯: 'bôi', 杰: 'kiệt', 松: 'tùng', 板: 'bản', 极: 'cực',
  构: 'cấu', 析: 'tích', 林: 'lâm', 果: 'quả', 枝: 'chi', 枪: 'thương', 架: 'giá',
  柄: 'bính', 某: 'mỗ', 染: 'nhiễm', 柔: 'nhu', 查: 'tra', 柳: 'liễu', 树: 'thụ',
  校: 'hiệu', 样: 'dạng', 核: 'hạch', 根: 'căn', 格: 'cách', 桃: 'đào',
  桌: 'trác', 桥: 'kiều', 桶: 'dũng', 梁: 'lương', 梅: 'mai', 梦: 'mộng',
  梯: 'thê', 械: 'giới', 检: 'kiểm', 棉: 'miên', 棋: 'kỳ', 棒: 'bổng', 森: 'sâm',
  椅: 'ỷ', 植: 'thực', 楼: 'lâu', 概: 'khái', 榜: 'bảng', 模: 'mô', 樱: 'anh',
  橙: 'tranh', 欠: 'khiếm', 次: 'thứ', 欢: 'hoan', 欣: 'hân', 欧: 'âu', 欲: 'dục',
  歉: 'khiểm', 歌: 'ca', 止: 'chỉ', 正: 'chính', 此: 'thử', 步: 'bộ', 武: 'vũ',
  歪: 'oai', 死: 'tử', 殊: 'thù', 残: 'tàn', 段: 'đoạn', 母: 'mẫu', 每: 'mỗi',
  毒: 'độc', 比: 'tỷ', 毕: 'tất', 毛: 'mao', 民: 'dân', 气: 'khí', 水: 'thủy',
  永: 'vĩnh', 求: 'cầu', 汁: 'trấp', 汇: 'hối', 汗: 'hãn', 江: 'giang', 池: 'trì',
  污: 'ô', 汤: 'thang', 汪: 'uông', 汽: 'khí', 沃: 'ốc', 沉: 'trầm', 沐: 'mộc',
  沙: 'sa', 沟: 'câu', 没: 'một', 河: 'hà', 油: 'du', 治: 'trị', 沿: 'duyên',
  泉: 'tuyền', 泊: 'bạc', 泌: 'bí', 法: 'pháp', 泡: 'phao', 波: 'ba', 泥: 'nê',
  注: 'chú', 泪: 'lệ', 泰: 'thái', 泳: 'vịnh', 泽: 'trạch', 洁: 'khiết',
  洋: 'dương', 洒: 'sái', 洗: 'tẩy', 洞: 'động', 津: 'tân', 洪: 'hồng',
  洲: 'châu', 活: 'hoạt', 派: 'phái', 流: 'lưu', 浅: 'thiển', 测: 'trắc',
  济: 'tế', 浏: 'lưu', 浑: 'hồn', 浓: 'nùng', 浪: 'lãng', 浮: 'phù', 浴: 'dục',
  海: 'hải', 消: 'tiêu', 涉: 'thiệp', 涌: 'dũng', 涛: 'đào', 涨: 'trướng',
  涩: 'sáp', 液: 'dịch', 淋: 'lâm', 淡: 'đạm', 深: 'thâm', 混: 'hỗn', 清: 'thanh',
  渐: 'tiệm', 渠: 'cừ', 渡: 'độ', 温: 'ôn', 港: 'cảng', 渴: 'khát', 游: 'du',
  湖: 'hồ', 湾: 'loan', 源: 'nguyên', 溜: 'lưu', 溪: 'khê', 滑: 'hoạt',
  满: 'mãn', 滚: 'cổn', 滴: 'trích', 漂: 'phiêu', 漏: 'lậu', 演: 'diễn',
  漠: 'mạc', 漫: 'mạn', 潜: 'tiềm', 潮: 'triều', 澡: 'táo', 激: 'kích', 火: 'hỏa',
  灭: 'diệt', 灯: 'đăng', 灰: 'hôi', 灵: 'linh', 灶: 'táo', 灾: 'tai', 炉: 'lô',
  炎: 'viêm', 炒: 'sao', 炮: 'pháo', 炸: 'tạc', 点: 'điểm', 炼: 'luyện',
  烂: 'lạn', 烈: 'liệt', 烟: 'yên', 烤: 'khảo', 热: 'nhiệt', 焦: 'tiêu',
  然: 'nhiên', 煮: 'chử', 熊: 'hùng', 熟: 'thục', 燃: 'nhiên', 燥: 'táo',
  爆: 'bạo', 爪: 'trảo', 爬: 'ba', 爱: 'ái', 爵: 'tước', 父: 'phụ', 爷: 'gia',
  爸: 'ba', 爽: 'sảng', 片: 'phiến', 版: 'bản', 牌: 'bài', 牙: 'nha',
  牛: 'ngưu', 牢: 'lao', 牧: 'mục', 物: 'vật', 牲: 'sinh', 特: 'đặc', 牵: 'khiên',
  犀: 'tê', 犬: 'khuyển', 犯: 'phạm', 状: 'trạng', 狂: 'cuồng', 狗: 'cẩu',
  狠: 'ngận', 狮: 'sư', 独: 'độc', 狭: 'hiệp', 狱: 'ngục', 狼: 'lang', 猛: 'mãnh',
  猜: 'sai', 猪: 'trư', 猫: 'miêu', 献: 'hiến', 猴: 'hầu', 玄: 'huyền', 率: 'suất',
  玉: 'ngọc', 王: 'vương', 玩: 'ngoạn', 环: 'hoàn', 现: 'hiện', 玲: 'linh',
  珍: 'trân', 珠: 'châu', 班: 'ban', 球: 'cầu', 理: 'lý', 琴: 'cầm', 瑞: 'thụy',
  瑟: 'sắt', 瓜: 'qua', 瓶: 'bình', 甜: 'điềm', 生: 'sinh', 用: 'dụng', 甩: 'súy',
  田: 'điền', 由: 'do', 甲: 'giáp', 申: 'thân', 电: 'điện', 男: 'nam', 甸: 'điện',
  画: 'họa', 界: 'giới', 留: 'lưu', 略: 'lược', 番: 'phiên', 疑: 'nghi',
  疗: 'liệu', 疯: 'phong', 疲: 'bì', 疼: 'đông', 病: 'bệnh', 症: 'chứng',
  痕: 'ngân', 痛: 'thống', 瘦: 'sấu', 登: 'đăng', 白: 'bạch', 百: 'bách',
  的: 'đích', 皆: 'giai', 皇: 'hoàng', 皮: 'bì', 盆: 'bồn', 盈: 'doanh',
  益: 'ích', 盐: 'diêm', 监: 'giám', 盒: 'hạp', 盖: 'cái', 盘: 'bàn', 盛: 'thịnh',
  盟: 'minh', 目: 'mục', 盲: 'manh', 直: 'trực', 相: 'tương', 盼: 'phán',
  盾: 'thuẫn', 省: 'tỉnh', 看: 'khán', 真: 'chân', 眠: 'miên', 眷: 'quyến',
  眼: 'nhãn', 着: 'trước', 睁: 'tranh', 睛: 'tình', 睡: 'thụy', 督: 'đốc',
  瞧: 'tiều', 矛: 'mâu', 矣: 'hĩ', 知: 'tri', 短: 'đoản', 石: 'thạch', 矿: 'khoáng',
  码: 'mã', 砍: 'khảm', 研: 'nghiên', 破: 'phá', 础: 'sở', 硬: 'ngạnh',
  确: 'xác', 碗: 'oản', 碰: 'bính', 碱: 'kiềm', 碳: 'thán', 磁: 'từ', 示: 'thị',
  礼: 'lễ', 社: 'xã', 祖: 'tổ', 神: 'thần', 祝: 'chúc', 票: 'phiếu', 祸: 'họa',
  离: 'ly', 禁: 'cấm', 福: 'phúc', 秀: 'tú', 私: 'tư', 秋: 'thu', 种: 'chủng',
  科: 'khoa', 秒: 'miểu', 秘: 'bí', 租: 'tô', 秤: 'xứng', 积: 'tích', 称: 'xưng',
  移: 'di', 稀: 'hi', 程: 'trình', 稍: 'sảo', 税: 'thuế', 稳: 'ổn', 稻: 'đạo',
  穷: 'cùng', 空: 'không', 穿: 'xuyên', 突: 'đột', 窗: 'song', 窝: 'oa',
  立: 'lập', 站: 'trạm', 竞: 'cạnh', 章: 'chương', 童: 'đồng', 端: 'đoan',
  竹: 'trúc', 笋: 'duẩn', 笑: 'tiếu', 笔: 'bút', 笨: 'bổn', 笼: 'lung', 符: 'phù',
  第: 'đệ', 等: 'đẳng', 筋: 'cân', 筑: 'trúc', 答: 'đáp', 策: 'sách',
  筷: 'khoái', 简: 'giản', 算: 'toán', 管: 'quản', 箭: 'tiễn', 篇: 'thiên',
  籍: 'tịch', 米: 'mễ', 类: 'loại', 粉: 'phấn', 粒: 'lạp', 粗: 'thô', 粘: 'niêm',
  粥: 'chúc', 粮: 'lương', 精: 'tinh', 糊: 'hồ', 糕: 'cao', 糖: 'đường',
  素: 'tố', 索: 'tác', 紧: 'khẩn', 紫: 'tử', 累: 'lũy', 细: 'tế',
  织: 'chức', 终: 'chung', 组: 'tổ', 绍: 'thiệu', 经: 'kinh', 结: 'kết',
  绕: 'nhiễu', 绘: 'hội', 给: 'cấp', 络: 'lạc', 绝: 'tuyệt', 绞: 'giảo',
  统: 'thống', 继: 'kế', 绩: 'tích', 绪: 'tự', 续: 'tục', 绳: 'thằng', 维: 'duy',
  绵: 'miên', 综: 'tổng', 绿: 'lục', 缓: 'hoãn', 编: 'biên', 缘: 'duyên',
  缩: 'súc', 缴: 'kiểu', 网: 'võng', 罐: 'quán', 罕: 'hãn', 罚: 'phạt',
  罢: 'bãi', 罩: 'tráo', 罪: 'tội', 置: 'trí', 羊: 'dương', 美: 'mỹ', 羞: 'tu',
  群: 'quần', 羽: 'vũ', 翁: 'ông', 翅: 'sí', 翻: 'phiên', 翼: 'dực', 老: 'lão',
  考: 'khảo', 者: 'giả', 而: 'nhi', 耍: 'sái', 耐: 'nại', 耕: 'canh', 耗: 'hao',
  耳: 'nhĩ', 耽: 'đam', 聊: 'liêu', 联: 'liên', 聘: 'sính', 聚: 'tụ', 聪: 'thông',
  肉: 'nhục', 肌: 'cơ', 肚: 'đỗ', 肝: 'can', 肠: 'tràng', 股: 'cổ', 肥: 'phì',
  肩: 'kiên', 肯: 'khẳng', 育: 'dục', 背: 'bối', 胖: 'bàn', 胜: 'thắng',
  胞: 'bào', 胡: 'hồ', 胶: 'giao', 胸: 'hung', 能: 'năng', 脂: 'chi', 脆: 'thúy',
  脏: 'tạng', 脑: 'não', 脖: 'bột', 脚: 'cước', 脱: 'thoát', 脸: 'kiểm',
  腐: 'hủ', 腰: 'yêu', 腹: 'phúc', 腿: 'thối', 膀: 'bàng', 膊: 'bác', 膜: 'mô',
  臂: 'tí', 臭: 'xú', 自: 'tự', 至: 'chí', 致: 'trí', 舌: 'thiệt',
  舍: 'xá', 舒: 'thư', 舞: 'vũ', 舟: 'chu', 航: 'hàng', 般: 'bàn', 船: 'thuyền',
  艇: 'đĩnh', 良: 'lương', 艰: 'gian', 色: 'sắc', 艺: 'nghệ', 节: 'tiết',
  芝: 'chi', 芬: 'phân', 花: 'hoa', 芳: 'phương', 芽: 'nha', 苇: 'vi', 苗: 'miêu',
  苛: 'hà', 若: 'nhược', 苦: 'khổ', 英: 'anh', 茂: 'mậu', 范: 'phạm', 茄: 'gia',
  茅: 'mao', 茶: 'trà', 草: 'thảo', 荒: 'hoang', 荡: 'đãng', 荣: 'vinh',
  药: 'dược', 荷: 'hà', 莫: 'mạc', 菜: 'thái', 营: 'doanh', 落: 'lạc', 著: 'trứ',
  葡: 'bồ', 葱: 'thông', 蒙: 'mông', 蒸: 'chưng', 蓝: 'lam', 蔬: 'sơ', 薄: 'bạc',
  藏: 'tàng', 虎: 'hổ', 虑: 'lự', 虫: 'trùng', 虹: 'hồng', 蛇: 'xà', 蛋: 'đản',
  蜂: 'phong', 蜜: 'mật', 蝶: 'điệp', 融: 'dung', 血: 'huyết', 行: 'hành',
  街: 'nhai', 衡: 'hành', 衣: 'y', 补: 'bổ', 表: 'biểu', 衬: 'sấn', 衫: 'sam',
  袋: 'đại', 袖: 'tụ', 被: 'bị', 裁: 'tài', 裂: 'liệt', 装: 'trang', 裕: 'dụ',
  裤: 'khố', 西: 'tây', 要: 'yếu', 覆: 'phúc', 见: 'kiến', 观: 'quan',
  规: 'quy', 视: 'thị', 览: 'lãm', 觉: 'giác', 角: 'giác', 解: 'giải', 触: 'xúc',
  言: 'ngôn', 誉: 'dự', 誓: 'thệ', 警: 'cảnh', 计: 'kế', 订: 'đính', 认: 'nhận',
  讨: 'thảo', 让: 'nhượng', 训: 'huấn', 议: 'nghị', 记: 'ký', 讲: 'giảng',
  许: 'hứa', 论: 'luận', 设: 'thiết', 访: 'phỏng', 证: 'chứng', 评: 'bình',
  识: 'thức', 诉: 'tố', 词: 'từ', 译: 'dịch', 试: 'thí', 诗: 'thi', 询: 'tuân',
  该: 'cai', 详: 'tường', 语: 'ngữ', 误: 'ngộ', 说: 'thuyết', 请: 'thỉnh',
  诸: 'chư', 读: 'độc', 课: 'khóa', 谁: 'thùy', 调: 'điều', 谅: 'lượng',
  谈: 'đàm', 谊: 'nghị', 谎: 'hoang', 谓: 'vị', 谢: 'tạ', 谱: 'phổ', 谷: 'cốc',
  豆: 'đậu', 象: 'tượng', 豪: 'hào', 貌: 'mạo', 贝: 'bối', 贞: 'trinh', 负: 'phụ',
  贡: 'cống', 财: 'tài', 责: 'trách', 贤: 'hiền', 败: 'bại', 货: 'hóa', 质: 'chất',
  贩: 'phiến', 贪: 'tham', 贫: 'bần', 购: 'cấu', 贯: 'quán', 贴: 'thiếp',
  贵: 'quý', 贷: 'thải', 贸: 'mậu', 费: 'phí', 贺: 'hạ', 贼: 'tặc', 资: 'tư',
  赏: 'thưởng', 赐: 'tứ', 赔: 'bồi', 赖: 'lại', 赛: 'trại', 赞: 'tán', 赠: 'tặng',
  赢: 'doanh', 赤: 'xích', 走: 'tẩu', 赴: 'phó', 赶: 'cản', 起: 'khởi', 趁: 'sấn',
  超: 'siêu', 越: 'việt', 趋: 'xu', 足: 'túc', 趴: 'ba', 趣: 'thú', 跌: 'điệt',
  跑: 'bào', 距: 'cự', 跟: 'cân', 跨: 'khóa', 路: 'lộ', 跳: 'khiêu', 践: 'tiễn',
  踏: 'đạp', 踢: 'thích', 踩: 'thải', 身: 'thân', 躬: 'cung', 躲: 'đóa',
  车: 'xa', 轨: 'quỹ', 转: 'chuyển', 轮: 'luân', 软: 'nhuyễn', 轰: 'oanh',
  轻: 'khinh', 载: 'tải', 较: 'giảo', 辆: 'lượng', 辈: 'bối', 辉: 'huy',
  辑: 'tập', 输: 'thâu', 辛: 'tân', 辞: 'từ', 辣: 'lạt', 辨: 'biện', 辩: 'biện',
  辰: 'thần', 辱: 'nhục', 边: 'biên', 达: 'đạt', 迁: 'thiên', 迅: 'tấn',
  过: 'quá', 迈: 'mại', 迎: 'nghênh', 运: 'vận', 近: 'cận', 返: 'phản',
  还: 'hoàn', 进: 'tiến', 远: 'viễn', 违: 'vi', 连: 'liên', 迟: 'trì', 迪: 'địch',
  迫: 'bách', 迷: 'mê', 迹: 'tích', 追: 'truy', 退: 'thoái', 送: 'tống',
  适: 'thích', 逃: 'đào', 逆: 'nghịch', 选: 'tuyển', 逊: 'tốn', 透: 'thấu',
  逐: 'trục', 递: 'đệ', 途: 'đồ', 通: 'thông', 逛: 'cuống', 逝: 'thệ',
  速: 'tốc', 造: 'tạo', 逢: 'phùng', 逮: 'đãi', 逼: 'bức', 遇: 'ngộ', 遍: 'biến',
  道: 'đạo', 遗: 'di', 遭: 'tao', 遮: 'già', 遵: 'tuân', 避: 'tị', 邀: 'yêu',
  邮: 'bưu', 邻: 'lân', 郊: 'giao', 部: 'bộ', 都: 'đô', 配: 'phối', 酒: 'tửu',
  酸: 'toan', 酿: 'nhưỡng', 醉: 'túy', 醋: 'thố', 醒: 'tỉnh', 采: 'thái',
  释: 'thích', 里: 'lý', 重: 'trọng', 野: 'dã', 量: 'lượng', 金: 'kim',
  针: 'châm', 钉: 'đinh', 钙: 'cai', 钞: 'sao', 钟: 'chung', 钢: 'cương',
  钥: 'thược', 钱: 'tiền', 钻: 'toản', 铁: 'thiết', 铃: 'linh', 铅: 'diên',
  银: 'ngân', 铺: 'phô', 链: 'liên', 销: 'tiêu', 锁: 'tỏa', 锅: 'oa', 锋: 'phong',
  错: 'thác', 锦: 'cẩm', 键: 'kiện', 镇: 'trấn', 镜: 'kính', 长: 'trường',
  门: 'môn', 闪: 'thiểm', 闭: 'bế', 问: 'vấn', 闯: 'sấm', 闲: 'nhàn', 间: 'gian',
  闷: 'muộn', 闹: 'náo', 闻: 'văn', 阁: 'các', 阅: 'duyệt', 阔: 'khoát',
  队: 'đội', 阴: 'âm', 防: 'phòng', 阳: 'dương', 阵: 'trận', 阶: 'giai',
  阻: 'trở', 附: 'phụ', 际: 'tế', 陆: 'lục', 陈: 'trần', 降: 'giáng',
  限: 'hạn', 院: 'viện', 除: 'trừ', 险: 'hiểm', 陪: 'bồi', 隆: 'long',
  随: 'tùy', 隐: 'ẩn', 隔: 'cách', 障: 'chướng', 隶: 'lệ', 雀: 'tước',
  雄: 'hùng', 集: 'tập', 雇: 'cố', 雕: 'điêu', 雨: 'vũ', 雪: 'tuyết',
  零: 'linh', 雷: 'lôi', 雾: 'vụ', 需: 'nhu', 震: 'chấn', 霜: 'sương',
  霞: 'hà', 露: 'lộ', 青: 'thanh', 靖: 'tĩnh', 静: 'tĩnh', 非: 'phi', 靠: 'kháo',
  面: 'diện', 革: 'cách', 鞋: 'hài', 鞭: 'tiên', 韩: 'hàn', 音: 'âm', 韵: 'vận',
  页: 'hiệt', 顶: 'đỉnh', 项: 'hạng', 顺: 'thuận', 须: 'tu', 顿: 'đốn',
  预: 'dự', 顾: 'cố', 顽: 'ngoan', 颁: 'ban', 颂: 'tụng', 领: 'lĩnh', 颇: 'phả', 频: 'tần', 颗: 'khỏa', 题: 'đề', 颜: 'nhan', 额: 'ngạch',
  风: 'phong', 飘: 'phiêu', 飞: 'phi', 食: 'thực', 饥: 'cơ', 饭: 'phạn',
  饮: 'ẩm', 饰: 'sức', 饱: 'bão', 饲: 'tự', 饼: 'bính', 饺: 'giáo', 饿: 'ngạ',
  馆: 'quán', 馒: 'màn', 首: 'thủ', 香: 'hương', 马: 'mã', 驱: 'khu', 驶: 'sử',
  驻: 'trú', 驾: 'giá', 骂: 'mạ', 骄: 'kiêu', 骑: 'kỵ', 骗: 'phiến', 骤: 'sậu',
  骨: 'cốt', 高: 'cao', 鬼: 'quỷ', 魂: 'hồn', 魄: 'phách', 魅: 'mị',
  魔: 'ma', 鱼: 'ngư', 鲁: 'lỗ', 鲜: 'tiên', 鸟: 'điểu', 鸡: 'kê', 鸣: 'minh',
  鸭: 'áp', 鸿: 'hồng', 鹅: 'nga', 鹏: 'bằng', 鹰: 'ưng', 鹿: 'lộc', 麦: 'mạch',
  麻: 'ma', 黄: 'hoàng', 黑: 'hắc', 默: 'mặc', 鼓: 'cổ', 鼠: 'thử', 鼻: 'tị',
  齐: 'tề', 齿: 'xỉ', 龄: 'linh', 龙: 'long', 龟: 'quy',
};

// Remove any accidental non-single-character keys that slipped in during authoring.
for (const key of Object.keys(HAN_VIET_MAP)) {
  if ([...key].length !== 1 || !HAN_VIET_MAP[key]) {
    delete HAN_VIET_MAP[key];
  }
}

const HAN_REGEX = /[㐀-鿿豈-﫿]/;

/**
 * Compose the Sino-Vietnamese reading for a word/phrase by joining the reading of
 * each Han character. Returns null when no character has a known reading, so callers
 * can gracefully omit the field.
 */
export const toHanViet = (text) => {
  const chars = [...String(text || '')].filter((char) => HAN_REGEX.test(char));

  if (chars.length === 0) {
    return null;
  }

  const readings = chars.map((char) => HAN_VIET_MAP[char]);

  if (readings.every((reading) => !reading)) {
    return null;
  }

  return readings.map((reading) => reading || '?').join(' ');
};
