-- ==============================================================================
-- DEPRECATED: This file is no longer used for database initialization.
-- All baseline standard content (lessons, vocabulary, grammar, achievements,
-- chat scenarios) have been migrated and localized (en/vi) into the
-- `/data` directory structure.
--
-- During database initialization (`npm run db:init`), the script
-- `server/scripts/import_data.cjs` is executed automatically to fully sync
-- the current schema with the JSON source-of-truth from the `/data` folder.
-- ==============================================================================

