export type RadicalFrequency = "high" | "medium" | "low";

export interface KangxiRadical {
  number: number;
  radical: string;
  pinyin: string;
  meaningVi: string;
  meaningEn: string;
  strokeCount: number;
  examples: string[];
  frequency: RadicalFrequency;
  variants?: string[];
}

const high = new Set([
  9, 30, 32, 38, 39, 40, 42, 46, 61, 64, 72, 74, 75, 85, 86, 94, 96, 102, 109, 118, 120, 140, 142, 149, 154, 157, 159, 162, 163, 167, 169, 170, 173, 181, 184, 187,
]);

const medium = new Set([
  1, 2, 3, 4, 7, 8, 12, 15, 18, 19, 24, 25, 29, 31, 37, 50, 53, 57, 60, 62, 73, 76, 77, 82, 84, 93, 100, 113, 115, 117, 123, 128, 130, 145, 147, 148, 150, 156, 158, 160, 161, 172, 174, 180, 182, 185, 188, 194, 195, 196, 201, 203, 209, 211, 212,
]);

const frequencyFor = (number: number): RadicalFrequency =>
  high.has(number) ? "high" : medium.has(number) ? "medium" : "low";

const r = (
  number: number,
  radical: string,
  pinyin: string,
  meaningVi: string,
  meaningEn: string,
  strokeCount: number,
  examples: string[],
  variants?: string[],
): KangxiRadical => ({
  number,
  radical,
  pinyin,
  meaningVi,
  meaningEn,
  strokeCount,
  examples,
  frequency: frequencyFor(number),
  variants,
});

export const KANGXI_RADICALS: KangxiRadical[] = [
  r(1, "一", "yī", "một, nét ngang", "one, horizontal stroke", 1, ["一", "丁", "上"]),
  r(2, "丨", "gǔn", "nét sổ dọc", "vertical stroke", 1, ["中", "串", "丰"]),
  r(3, "丶", "zhǔ", "chấm", "dot", 1, ["主", "丸", "丹"]),
  r(4, "丿", "piě", "nét phẩy", "slash stroke", 1, ["乃", "久", "乂"]),
  r(5, "乙", "yǐ", "can Ất, nét cong", "second, curved stroke", 1, ["乙", "九", "也"], ["乚"]),
  r(6, "亅", "jué", "nét móc", "hook stroke", 1, ["了", "事", "予"]),
  r(7, "二", "èr", "hai", "two", 2, ["二", "云", "五"]),
  r(8, "亠", "tóu", "đầu, mái trên", "lid, top", 2, ["京", "亡", "六"]),
  r(9, "人", "rén", "người", "person", 2, ["人", "你", "他"], ["亻"]),
  r(10, "儿", "ér", "chân người", "legs, walking person", 2, ["儿", "先", "兄"]),
  r(11, "入", "rù", "vào", "enter", 2, ["入", "內", "全"]),
  r(12, "八", "bā", "tám, phân tách", "eight, divide", 2, ["八", "公", "共"], ["丷"]),
  r(13, "冂", "jiōng", "khung mở", "open frame", 2, ["冂", "内", "再"]),
  r(14, "冖", "mì", "mái che", "cover", 2, ["冖", "写", "军"]),
  r(15, "冫", "bīng", "băng", "ice", 2, ["冰", "冷", "冲"]),
  r(16, "几", "jī", "bàn nhỏ", "small table", 2, ["几", "凡", "凯"]),
  r(17, "凵", "qū", "hộp mở", "open box", 2, ["凶", "出", "函"]),
  r(18, "刀", "dāo", "dao", "knife", 2, ["刀", "分", "到"], ["刂"]),
  r(19, "力", "lì", "sức lực", "strength, power", 2, ["力", "加", "动"]),
  r(20, "勹", "bāo", "bao bọc", "wrap", 2, ["包", "句", "勺"]),
  r(21, "匕", "bǐ", "thìa, muỗng", "spoon", 2, ["匕", "化", "北"]),
  r(22, "匚", "fāng", "hộp vuông", "box", 2, ["区", "医", "匠"]),
  r(23, "匸", "xǐ", "che giấu", "conceal", 2, ["匹", "匿", "区"]),
  r(24, "十", "shí", "mười", "ten", 2, ["十", "古", "午"]),
  r(25, "卜", "bǔ", "bói toán", "divination", 2, ["卜", "占", "卡"]),
  r(26, "卩", "jié", "đốt tre, con dấu", "seal, joint", 2, ["印", "即", "却"], ["㔾"]),
  r(27, "厂", "hǎn", "vách đá", "cliff", 2, ["厅", "原", "历"]),
  r(28, "厶", "sī", "riêng tư", "private", 2, ["私", "去", "参"]),
  r(29, "又", "yòu", "lại, tay phải", "again, right hand", 2, ["又", "友", "取"]),
  r(30, "口", "kǒu", "miệng", "mouth", 3, ["口", "吗", "喝"]),
  r(31, "囗", "wéi", "khung bao quanh", "enclosure", 3, ["国", "园", "回"]),
  r(32, "土", "tǔ", "đất", "earth, soil", 3, ["土", "地", "城"]),
  r(33, "士", "shì", "sĩ, học giả", "scholar", 3, ["士", "声", "壶"]),
  r(34, "夂", "zhǐ", "đi đến", "go, arrive", 3, ["处", "备", "复"]),
  r(35, "夊", "suī", "đi chậm", "walk slowly", 3, ["夏", "夔", "夊"]),
  r(36, "夕", "xī", "buổi tối", "evening", 3, ["夕", "外", "多"]),
  r(37, "大", "dà", "to lớn", "big, great", 3, ["大", "天", "太"]),
  r(38, "女", "nǚ", "phụ nữ", "woman", 3, ["女", "好", "妈"]),
  r(39, "子", "zǐ", "con, trẻ", "child", 3, ["子", "学", "字"]),
  r(40, "宀", "mián", "mái nhà", "roof", 3, ["家", "安", "字"]),
  r(41, "寸", "cùn", "tấc", "inch", 3, ["对", "寺", "封"]),
  r(42, "小", "xiǎo", "nhỏ", "small", 3, ["小", "少", "尖"], ["⺌"]),
  r(43, "尢", "wāng", "khập khiễng", "lame", 3, ["尤", "就", "尬"], ["尣"]),
  r(44, "尸", "shī", "xác, thân nằm", "corpse", 3, ["尸", "层", "居"]),
  r(45, "屮", "chè", "mầm cây", "sprout", 3, ["屯", "屮", "屰"]),
  r(46, "山", "shān", "núi", "mountain", 3, ["山", "岁", "岛"]),
  r(47, "巛", "chuān", "sông", "river", 3, ["巡", "巢", "川"], ["川"]),
  r(48, "工", "gōng", "công việc", "work, labor", 3, ["工", "左", "巧"]),
  r(49, "己", "jǐ", "bản thân", "oneself", 3, ["己", "已", "记"]),
  r(50, "巾", "jīn", "khăn, vải", "cloth, napkin", 3, ["巾", "布", "希"]),
  r(51, "干", "gān", "khô, can", "dry", 3, ["干", "平", "年"]),
  r(52, "幺", "yāo", "nhỏ, tơ non", "tiny, thread", 3, ["幻", "幼", "幺"]),
  r(53, "广", "guǎng", "mái nhà rộng", "wide shelter", 3, ["广", "店", "床"]),
  r(54, "廴", "yǐn", "bước dài", "long stride", 3, ["建", "延", "廷"]),
  r(55, "廾", "gǒng", "hai tay nâng", "two hands", 3, ["开", "弄", "异"]),
  r(56, "弋", "yì", "bắn bằng dây", "shoot with cord", 3, ["式", "弋", "代"]),
  r(57, "弓", "gōng", "cung", "bow", 3, ["弓", "张", "强"]),
  r(58, "彐", "jì", "đầu heo", "pig's head", 3, ["归", "当", "录"], ["彑"]),
  r(59, "彡", "shān", "lông, nét trang trí", "bristle, ornament", 3, ["形", "影", "彩"]),
  r(60, "彳", "chì", "bước chân trái", "step, left foot", 3, ["很", "往", "行"]),
  r(61, "心", "xīn", "tim, tâm", "heart, mind", 4, ["心", "想", "快"], ["忄", "⺗"]),
  r(62, "戈", "gē", "giáo mác", "halberd, spear", 4, ["戈", "成", "我"]),
  r(63, "戶", "hù", "cửa một cánh", "door, household", 4, ["户", "房", "所"], ["户"]),
  r(64, "手", "shǒu", "tay", "hand", 4, ["手", "打", "拿"], ["扌"]),
  r(65, "支", "zhī", "nhánh, chống đỡ", "branch, support", 4, ["支", "枝", "技"]),
  r(66, "攴", "pū", "đánh nhẹ", "tap, strike", 4, ["收", "改", "教"], ["攵"]),
  r(67, "文", "wén", "văn, chữ viết", "script, writing", 4, ["文", "这", "斋"]),
  r(68, "斗", "dǒu", "đấu, gầu đong", "dipper, measure", 4, ["斗", "料", "斜"]),
  r(69, "斤", "jīn", "rìu, cân", "axe, catty", 4, ["斤", "新", "断"]),
  r(70, "方", "fāng", "phương, vuông", "square, direction", 4, ["方", "旅", "族"]),
  r(71, "无", "wú", "không", "not, without", 4, ["无", "既", "旡"], ["旡"]),
  r(72, "日", "rì", "mặt trời, ngày", "sun, day", 4, ["日", "明", "时"]),
  r(73, "曰", "yuē", "nói rằng", "say", 4, ["曰", "最", "曹"]),
  r(74, "月", "yuè", "trăng, tháng", "moon, month", 4, ["月", "有", "朋"]),
  r(75, "木", "mù", "cây, gỗ", "tree, wood", 4, ["木", "林", "校"]),
  r(76, "欠", "qiàn", "thiếu, ngáp", "lack, yawn", 4, ["欠", "次", "欢"]),
  r(77, "止", "zhǐ", "dừng lại", "stop", 4, ["止", "正", "步"]),
  r(78, "歹", "dǎi", "xấu, chết", "bad, death", 4, ["死", "残", "歹"], ["歺"]),
  r(79, "殳", "shū", "binh khí", "weapon", 4, ["段", "殿", "杀"]),
  r(80, "毋", "wú", "chớ, đừng", "do not", 4, ["母", "每", "毒"]),
  r(81, "比", "bǐ", "so sánh", "compare", 4, ["比", "皆", "昆"]),
  r(82, "毛", "máo", "lông", "fur, hair", 4, ["毛", "笔", "毯"]),
  r(83, "氏", "shì", "họ tộc", "clan, family", 4, ["氏", "纸", "民"]),
  r(84, "气", "qì", "khí, hơi", "air, steam", 4, ["气", "汽", "氧"]),
  r(85, "水", "shuǐ", "nước", "water", 4, ["水", "河", "海"], ["氵", "氺"]),
  r(86, "火", "huǒ", "lửa", "fire", 4, ["火", "热", "灯"], ["灬"]),
  r(87, "爪", "zhǎo", "móng vuốt", "claw", 4, ["爪", "爱", "受"], ["爫"]),
  r(88, "父", "fù", "cha", "father", 4, ["父", "爸", "爹"]),
  r(89, "爻", "yáo", "hào, vạch quẻ", "trigram lines", 4, ["爻", "爽", "爾"]),
  r(90, "爿", "pán", "mảnh gỗ tách", "split wood", 4, ["壮", "状", "牆"], ["丬"]),
  r(91, "片", "piàn", "mảnh, lát", "slice, piece", 4, ["片", "版", "牌"]),
  r(92, "牙", "yá", "răng nanh", "tooth, fang", 4, ["牙", "呀", "雅"]),
  r(93, "牛", "niú", "trâu, bò", "cow, ox", 4, ["牛", "物", "特"], ["牜"]),
  r(94, "犬", "quǎn", "chó", "dog", 4, ["狗", "猫", "状"], ["犭"]),
  r(95, "玄", "xuán", "huyền, sâu xa", "profound, dark", 5, ["玄", "率", "玆"]),
  r(96, "玉", "yù", "ngọc", "jade", 5, ["玉", "现", "理"], ["王"]),
  r(97, "瓜", "guā", "dưa", "melon", 5, ["瓜", "孤", "瓢"]),
  r(98, "瓦", "wǎ", "ngói", "tile", 5, ["瓦", "瓶", "瓷"]),
  r(99, "甘", "gān", "ngọt", "sweet", 5, ["甘", "甜", "某"]),
  r(100, "生", "shēng", "sinh, sống", "birth, life", 5, ["生", "星", "産"]),
  r(101, "用", "yòng", "dùng", "use", 5, ["用", "甩", "甫"]),
  r(102, "田", "tián", "ruộng", "field", 5, ["田", "男", "界"]),
  r(103, "疋", "pǐ", "cuộn vải", "bolt of cloth", 5, ["疋", "疑", "楚"]),
  r(104, "疒", "nè", "bệnh tật", "sickness", 5, ["病", "痛", "痒"]),
  r(105, "癶", "bō", "hai chân dang", "legs apart", 5, ["登", "發", "癸"]),
  r(106, "白", "bái", "trắng", "white", 5, ["白", "的", "百"]),
  r(107, "皮", "pí", "da", "skin", 5, ["皮", "被", "坡"]),
  r(108, "皿", "mǐn", "đồ đựng", "dish, vessel", 5, ["皿", "盆", "盘"]),
  r(109, "目", "mù", "mắt", "eye", 5, ["目", "看", "眼"]),
  r(110, "矛", "máo", "mâu, giáo", "spear, lance", 5, ["矛", "矜", "務"]),
  r(111, "矢", "shǐ", "mũi tên", "arrow", 5, ["矢", "知", "短"]),
  r(112, "石", "shí", "đá", "stone", 5, ["石", "破", "硬"]),
  r(113, "示", "shì", "thờ cúng, chỉ thị", "worship, show", 5, ["示", "神", "礼"], ["礻"]),
  r(114, "禸", "róu", "dấu chân", "track, footprint", 5, ["禹", "离", "禸"]),
  r(115, "禾", "hé", "lúa", "grain, cereal", 5, ["禾", "秋", "种"]),
  r(116, "穴", "xué", "hang, lỗ", "cave, hole", 5, ["穴", "空", "穿"]),
  r(117, "立", "lì", "đứng", "stand", 5, ["立", "站", "音"]),
  r(118, "竹", "zhú", "tre", "bamboo", 6, ["竹", "笑", "笔"], ["⺮"]),
  r(119, "米", "mǐ", "gạo", "rice", 6, ["米", "精", "糖"]),
  r(120, "糸", "mì", "tơ, sợi", "silk, thread", 6, ["丝", "经", "红"], ["纟"]),
  r(121, "缶", "fǒu", "vò, chum", "jar, pottery", 6, ["缶", "缺", "罐"]),
  r(122, "网", "wǎng", "lưới", "net", 6, ["网", "罗", "罪"], ["罒", "罓"]),
  r(123, "羊", "yáng", "dê, cừu", "sheep, goat", 6, ["羊", "美", "群"], ["⺶"]),
  r(124, "羽", "yǔ", "lông vũ", "feather", 6, ["羽", "习", "翔"]),
  r(125, "老", "lǎo", "già, lão", "old, aged", 6, ["老", "考", "者"], ["耂"]),
  r(126, "而", "ér", "mà, râu", "and, beard", 6, ["而", "耐", "耍"]),
  r(127, "耒", "lěi", "cày", "plow", 6, ["耕", "耗", "耙"]),
  r(128, "耳", "ěr", "tai", "ear", 6, ["耳", "闻", "聪"]),
  r(129, "聿", "yù", "bút viết", "brush, pen", 6, ["聿", "律", "書"]),
  r(130, "肉", "ròu", "thịt", "meat, flesh", 6, ["肉", "脸", "脚"], ["月"]),
  r(131, "臣", "chén", "bề tôi", "minister, subject", 6, ["臣", "卧", "臨"]),
  r(132, "自", "zì", "tự mình", "self", 6, ["自", "息", "鼻"]),
  r(133, "至", "zhì", "đến", "arrive, reach", 6, ["至", "到", "致"]),
  r(134, "臼", "jiù", "cối giã", "mortar", 6, ["臼", "舅", "舊"]),
  r(135, "舌", "shé", "lưỡi", "tongue", 6, ["舌", "话", "甜"]),
  r(136, "舛", "chuǎn", "trái ngược", "contrary, oppose", 6, ["舛", "舞", "舜"]),
  r(137, "舟", "zhōu", "thuyền", "boat", 6, ["舟", "船", "航"]),
  r(138, "艮", "gèn", "quẻ Cấn, dừng", "stopping, Gen trigram", 6, ["艮", "很", "良"]),
  r(139, "色", "sè", "màu sắc", "color", 6, ["色", "艳", "艴"]),
  r(140, "艸", "cǎo", "cỏ, cây", "grass, plant", 6, ["草", "花", "茶"], ["艹"]),
  r(141, "虍", "hū", "hổ", "tiger", 6, ["虎", "虚", "虑"]),
  r(142, "虫", "chóng", "sâu, côn trùng", "insect, worm", 6, ["虫", "虽", "蛇"]),
  r(143, "血", "xuè", "máu", "blood", 6, ["血", "衅", "衄"]),
  r(144, "行", "xíng", "đi, hàng", "walk, row", 6, ["行", "街", "術"]),
  r(145, "衣", "yī", "áo, quần áo", "clothing", 6, ["衣", "袋", "被"], ["衤"]),
  r(146, "襾", "yà", "che phủ", "cover", 6, ["西", "要", "覆"], ["西", "覀"]),
  r(147, "見", "jiàn", "thấy", "see", 7, ["見", "视", "观"], ["见"]),
  r(148, "角", "jiǎo", "sừng, góc", "horn, angle", 7, ["角", "解", "触"]),
  r(149, "言", "yán", "lời nói", "speech, words", 7, ["言", "说", "语"], ["讠"]),
  r(150, "谷", "gǔ", "thung lũng", "valley", 7, ["谷", "欲", "豁"]),
  r(151, "豆", "dòu", "đậu", "bean", 7, ["豆", "短", "豌"]),
  r(152, "豕", "shǐ", "heo", "pig", 7, ["豕", "家", "象"]),
  r(153, "豸", "zhì", "loài thú dài thân", "long-bodied beast", 7, ["貌", "豹", "貓"]),
  r(154, "貝", "bèi", "vỏ sò, tiền", "shell, money", 7, ["貝", "财", "贵"], ["贝"]),
  r(155, "赤", "chì", "đỏ", "red", 7, ["赤", "赦", "赫"]),
  r(156, "走", "zǒu", "đi, chạy", "walk, run", 7, ["走", "起", "超"]),
  r(157, "足", "zú", "chân", "foot", 7, ["足", "跑", "路"], ["⻊"]),
  r(158, "身", "shēn", "thân thể", "body", 7, ["身", "躲", "躺"]),
  r(159, "車", "chē", "xe", "cart, vehicle", 7, ["車", "车", "转"], ["车"]),
  r(160, "辛", "xīn", "cay, đắng", "bitter, spicy", 7, ["辛", "辣", "辩"]),
  r(161, "辰", "chén", "thìn, thời gian", "time, dragon hour", 7, ["辰", "晨", "震"]),
  r(162, "辵", "chuò", "bước đi", "walk, movement", 7, ["这", "进", "道"], ["辶"]),
  r(163, "邑", "yì", "ấp, thành", "town, city", 7, ["都", "部", "那"], ["阝"]),
  r(164, "酉", "yǒu", "rượu, dậu", "wine, rooster hour", 7, ["酉", "酒", "酸"]),
  r(165, "釆", "biàn", "phân biệt", "distinguish", 7, ["釆", "番", "悉"]),
  r(166, "里", "lǐ", "làng, bên trong", "village, inside", 7, ["里", "重", "量"]),
  r(167, "金", "jīn", "kim loại, vàng", "metal, gold", 8, ["金", "钱", "钟"], ["钅"]),
  r(168, "長", "cháng", "dài, trưởng", "long, grow", 8, ["長", "长", "帳"], ["长"]),
  r(169, "門", "mén", "cửa", "gate, door", 8, ["門", "门", "问"], ["门"]),
  r(170, "阜", "fù", "gò, đồi", "mound, hill", 8, ["防", "院", "阳"], ["阝"]),
  r(171, "隶", "lì", "lệ, bắt kịp", "slave, catch up", 8, ["隶", "隷", "逮"]),
  r(172, "隹", "zhuī", "chim đuôi ngắn", "short-tailed bird", 8, ["隹", "谁", "难"]),
  r(173, "雨", "yǔ", "mưa", "rain", 8, ["雨", "雪", "雷"]),
  r(174, "青", "qīng", "xanh, thanh", "blue-green, young", 8, ["青", "请", "情"]),
  r(175, "非", "fēi", "không phải", "wrong, not", 8, ["非", "靠", "悲"]),
  r(176, "面", "miàn", "mặt, bề mặt", "face, surface", 9, ["面", "靣", "麵"]),
  r(177, "革", "gé", "da thuộc", "leather, hide", 9, ["革", "鞋", "鞭"]),
  r(178, "韋", "wéi", "da mềm", "soft leather", 9, ["韋", "韩", "韧"], ["韦"]),
  r(179, "韭", "jiǔ", "hẹ", "leek, chives", 9, ["韭", "韮", "韱"]),
  r(180, "音", "yīn", "âm thanh", "sound", 9, ["音", "韵", "章"]),
  r(181, "頁", "yè", "đầu, trang", "head, page", 9, ["頁", "页", "题"], ["页"]),
  r(182, "風", "fēng", "gió", "wind", 9, ["風", "风", "飘"], ["风"]),
  r(183, "飛", "fēi", "bay", "fly", 9, ["飛", "飞", "飜"], ["飞"]),
  r(184, "食", "shí", "ăn, thức ăn", "eat, food", 9, ["食", "饭", "饮"], ["饣"]),
  r(185, "首", "shǒu", "đầu, đầu tiên", "head, first", 9, ["首", "道", "馗"]),
  r(186, "香", "xiāng", "hương thơm", "fragrance", 9, ["香", "馥", "馨"]),
  r(187, "馬", "mǎ", "ngựa", "horse", 10, ["馬", "马", "骑"], ["马"]),
  r(188, "骨", "gǔ", "xương", "bone", 10, ["骨", "骼", "髓"]),
  r(189, "高", "gāo", "cao", "tall, high", 10, ["高", "髙", "敲"]),
  r(190, "髟", "biāo", "tóc dài", "long hair", 10, ["髟", "髮", "鬓"]),
  r(191, "鬥", "dòu", "đấu, đánh nhau", "fight", 10, ["鬥", "鬧", "鬨"]),
  r(192, "鬯", "chàng", "rượu cúng", "sacrificial wine", 10, ["鬯", "鬱", "鬰"]),
  r(193, "鬲", "lì", "nồi ba chân", "cauldron", 10, ["鬲", "融", "隔"]),
  r(194, "鬼", "guǐ", "quỷ, linh hồn", "ghost, spirit", 10, ["鬼", "魂", "魄"]),
  r(195, "魚", "yú", "cá", "fish", 11, ["魚", "鱼", "鲜"], ["鱼"]),
  r(196, "鳥", "niǎo", "chim", "bird", 11, ["鳥", "鸟", "鸡"], ["鸟"]),
  r(197, "鹵", "lǔ", "muối mỏ", "rock salt", 11, ["鹵", "卤", "鹹"], ["卤"]),
  r(198, "鹿", "lù", "hươu", "deer", 11, ["鹿", "麓", "麗"]),
  r(199, "麥", "mài", "lúa mì", "wheat", 11, ["麥", "麦", "麵"], ["麦"]),
  r(200, "麻", "má", "cây gai dầu", "hemp", 11, ["麻", "磨", "魔"]),
  r(201, "黃", "huáng", "màu vàng", "yellow", 12, ["黃", "黄", "黉"], ["黄"]),
  r(202, "黍", "shǔ", "kê nếp", "millet", 12, ["黍", "黎", "黏"]),
  r(203, "黑", "hēi", "đen", "black", 12, ["黑", "默", "点"]),
  r(204, "黹", "zhǐ", "thêu", "embroidery", 12, ["黹", "黼", "黻"]),
  r(205, "黽", "mǐn", "ếch, ba ba", "frog, turtle", 13, ["黽", "黾", "鼋"], ["黾"]),
  r(206, "鼎", "dǐng", "đỉnh, vạc ba chân", "tripod cauldron", 13, ["鼎", "鼏", "鼐"]),
  r(207, "鼓", "gǔ", "trống", "drum", 13, ["鼓", "鼕", "鼙"]),
  r(208, "鼠", "shǔ", "chuột", "rat, mouse", 13, ["鼠", "鼬", "鼹"]),
  r(209, "鼻", "bí", "mũi", "nose", 14, ["鼻", "鼾", "齉"]),
  r(210, "齊", "qí", "đều, tề", "even, uniform", 14, ["齊", "齐", "齋"], ["齐"]),
  r(211, "齒", "chǐ", "răng", "tooth", 15, ["齒", "齿", "龄"], ["齿"]),
  r(212, "龍", "lóng", "rồng", "dragon", 16, ["龍", "龙", "龚"], ["龙"]),
  r(213, "龜", "guī", "rùa", "turtle", 16, ["龜", "龟", "龠"], ["龟"]),
  r(214, "龠", "yuè", "sáo, nhạc khí cổ", "flute, ancient pipe", 17, ["龠", "龢", "龡"]),
];

export const RADICAL_STROKE_COUNTS = Array.from(
  new Set(KANGXI_RADICALS.map((radical) => radical.strokeCount)),
).sort((a, b) => a - b);
