export interface Word {
  id: string;
  simplified: string;
  traditional: string;
  pinyin: string;
  tones: number[];
  english: string;
  partOfSpeech: string; // 'noun' | 'verb' | 'adjective' | 'adverb' | 'pronoun' | 'numeral' | 'measure' | 'phrase'
  hskLevel: number;
  category: string;
}

export const VOCAB: Word[] = [
  // HSK 1 (150 words)
  { id: "wd_hello", simplified: "你好", traditional: "你好", pinyin: "nǐ hǎo", tones: [3,3], english: "hello", partOfSpeech: "phrase", hskLevel: 1, category: "Greetings" },
  { id: "wd_goodbye", simplified: "再见", traditional: "再见", pinyin: "zài jiàn", tones: [4,4], english: "goodbye", partOfSpeech: "phrase", hskLevel: 1, category: "Greetings" },
  { id: "wd_thankyou", simplified: "谢谢", traditional: "谢谢", pinyin: "xiè xiè", tones: [4,4], english: "thank you", partOfSpeech: "phrase", hskLevel: 1, category: "Greetings" },
  { id: "wd_youre_welcome", simplified: "不客气", traditional: "不客气", pinyin: "bú kè qì", tones: [2,4,4], english: "you're welcome", partOfSpeech: "phrase", hskLevel: 1, category: "Greetings" },
  { id: "wd_sorry", simplified: "对不起", traditional: "对不起", pinyin: "duì bù qǐ", tones: [4,4,3], english: "sorry", partOfSpeech: "phrase", hskLevel: 1, category: "Greetings" },
  { id: "wd_no_problem", simplified: "没关系", traditional: "没关系", pinyin: "méi guān xì", tones: [2,1,5], english: "it's ok/no problem", partOfSpeech: "phrase", hskLevel: 1, category: "Greetings" },
  { id: "wd_yes", simplified: "是", traditional: "是", pinyin: "shì", tones: [4], english: "yes / to be", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_no", simplified: "不", traditional: "不", pinyin: "bù", tones: [4], english: "no / not", partOfSpeech: "adverb", hskLevel: 1, category: "General" },
  { id: "wd_i", simplified: "我", traditional: "我", pinyin: "wǒ", tones: [3], english: "I / me", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_you", simplified: "你", traditional: "你", pinyin: "nǐ", tones: [3], english: "you", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_you_formal", simplified: "您", traditional: "您", pinyin: "nín", tones: [2], english: "you (formal)", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_he", simplified: "他", traditional: "他", pinyin: "tā", tones: [1], english: "he / him", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_she", simplified: "她", traditional: "她", pinyin: "tā", tones: [1], english: "she / her", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_we", simplified: "我们", traditional: "我们", pinyin: "wǒ men", tones: [3,5], english: "we / us", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_they", simplified: "他们", traditional: "他们", pinyin: "tā men", tones: [1,5], english: "they / them", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },

  { id: "wd_one", simplified: "一", traditional: "一", pinyin: "yī", tones: [1], english: "one", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_two", simplified: "二", traditional: "二", pinyin: "èr", tones: [4], english: "two", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_three", simplified: "三", traditional: "三", pinyin: "sān", tones: [1], english: "three", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_four", simplified: "四", traditional: "四", pinyin: "sì", tones: [4], english: "four", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_five", simplified: "五", traditional: "五", pinyin: "wǔ", tones: [3], english: "five", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_six", simplified: "六", traditional: "六", pinyin: "liù", tones: [4], english: "six", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_seven", simplified: "七", traditional: "七", pinyin: "qī", tones: [1], english: "seven", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_eight", simplified: "八", traditional: "八", pinyin: "bā", tones: [1], english: "eight", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_nine", simplified: "九", traditional: "九", pinyin: "jiǔ", tones: [3], english: "nine", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_ten", simplified: "十", traditional: "十", pinyin: "shí", tones: [2], english: "ten", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_hundred", simplified: "百", traditional: "百", pinyin: "bǎi", tones: [3], english: "hundred", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_thousand", simplified: "千", traditional: "千", pinyin: "qiān", tones: [1], english: "thousand", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },
  { id: "wd_zero", simplified: "零", traditional: "零", pinyin: "líng", tones: [2], english: "zero", partOfSpeech: "numeral", hskLevel: 1, category: "Numbers" },

  { id: "wd_dad", simplified: "爸爸", traditional: "爸爸", pinyin: "bà ba", tones: [4,5], english: "dad", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_mom", simplified: "妈妈", traditional: "妈妈", pinyin: "mā ma", tones: [1,5], english: "mom", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_older_brother", simplified: "哥哥", traditional: "哥哥", pinyin: "gē ge", tones: [1,5], english: "older brother", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_older_sister", simplified: "姐姐", traditional: "姐姐", pinyin: "jiě jie", tones: [3,5], english: "older sister", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_younger_brother", simplified: "弟弟", traditional: "弟弟", pinyin: "dì di", tones: [4,5], english: "younger brother", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_younger_sister", simplified: "妹妹", traditional: "妹妹", pinyin: "mèi mei", tones: [4,5], english: "younger sister", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_son", simplified: "儿子", traditional: "儿子", pinyin: "ér zi", tones: [2,5], english: "son", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_daughter", simplified: "女儿", traditional: "女兒", pinyin: "nǚ ér", tones: [3,2], english: "daughter", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_friend", simplified: "朋友", traditional: "朋友", pinyin: "péng yǒu", tones: [2,3], english: "friend", partOfSpeech: "noun", hskLevel: 1, category: "Family" },
  { id: "wd_teacher", simplified: "老师", traditional: "老師", pinyin: "lǎo shī", tones: [3,1], english: "teacher", partOfSpeech: "noun", hskLevel: 1, category: "School" },
  { id: "wd_student", simplified: "学生", traditional: "學生", pinyin: "xué shēng", tones: [2,1], english: "student", partOfSpeech: "noun", hskLevel: 1, category: "School" },
  { id: "wd_doctor", simplified: "医生", traditional: "醫生", pinyin: "yī shēng", tones: [1,1], english: "doctor", partOfSpeech: "noun", hskLevel: 1, category: "Health" },

  { id: "wd_eat", simplified: "吃", traditional: "吃", pinyin: "chī", tones: [1], english: "to eat", partOfSpeech: "verb", hskLevel: 1, category: "Food" },
  { id: "wd_drink", simplified: "喝", traditional: "喝", pinyin: "hē", tones: [1], english: "to drink", partOfSpeech: "verb", hskLevel: 1, category: "Food" },
  { id: "wd_rice", simplified: "米饭", traditional: "米飯", pinyin: "mǐ fàn", tones: [3,4], english: "rice", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_noodles", simplified: "面条", traditional: "麵條", pinyin: "miàn tiáo", tones: [4,2], english: "noodles", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_bread", simplified: "面包", traditional: "麵包", pinyin: "miàn bāo", tones: [4,1], english: "bread", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_water", simplified: "水", traditional: "水", pinyin: "shuǐ", tones: [3], english: "water", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_tea", simplified: "茶", traditional: "茶", pinyin: "chá", tones: [2], english: "tea", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_coffee", simplified: "咖啡", traditional: "咖啡", pinyin: "kā fēi", tones: [1,1], english: "coffee", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_apple", simplified: "苹果", traditional: "蘋果", pinyin: "píng guǒ", tones: [2,3], english: "apple", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_fish", simplified: "鱼", traditional: "魚", pinyin: "yú", tones: [2], english: "fish", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_chicken", simplified: "鸡", traditional: "雞", pinyin: "jī", tones: [1], english: "chicken", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_egg", simplified: "鸡蛋", traditional: "雞蛋", pinyin: "jī dàn", tones: [1,4], english: "egg", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_beef", simplified: "牛肉", traditional: "牛肉", pinyin: "niú ròu", tones: [2,4], english: "beef", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_delicious", simplified: "好吃", traditional: "好吃", pinyin: "hǎo chī", tones: [3,1], english: "delicious", partOfSpeech: "adjective", hskLevel: 1, category: "Food" },
  { id: "wd_spicy", simplified: "辣", traditional: "辣", pinyin: "là", tones: [4], english: "spicy", partOfSpeech: "adjective", hskLevel: 2, category: "Food" },

  { id: "wd_today", simplified: "今天", traditional: "今天", pinyin: "jīn tiān", tones: [1,1], english: "today", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_yesterday", simplified: "昨天", traditional: "昨天", pinyin: "zuó tiān", tones: [2,1], english: "yesterday", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_tomorrow", simplified: "明天", traditional: "明天", pinyin: "míng tiān", tones: [2,1], english: "tomorrow", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_morning", simplified: "早上", traditional: "早上", pinyin: "zǎo shang", tones: [3,5], english: "morning", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_afternoon", simplified: "下午", traditional: "下午", pinyin: "xià wǔ", tones: [4,3], english: "afternoon", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_evening", simplified: "晚上", traditional: "晚上", pinyin: "wǎn shang", tones: [3,5], english: "evening", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_hour", simplified: "小时", traditional: "小時", pinyin: "xiǎo shí", tones: [3,2], english: "hour", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_minute", simplified: "分钟", traditional: "分鐘", pinyin: "fēn zhōng", tones: [1,1], english: "minute", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_now", simplified: "现在", traditional: "現在", pinyin: "xiàn zài", tones: [4,4], english: "now", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_year", simplified: "年", traditional: "年", pinyin: "nián", tones: [2], english: "year", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_month", simplified: "月", traditional: "月", pinyin: "yuè", tones: [4], english: "month / moon", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_week", simplified: "星期", traditional: "星期", pinyin: "xīng qī", tones: [1,1], english: "week", partOfSpeech: "noun", hskLevel: 1, category: "Time" },
  { id: "wd_day", simplified: "天", traditional: "天", pinyin: "tiān", tones: [1], english: "day / sky", partOfSpeech: "noun", hskLevel: 1, category: "Time" },

  { id: "wd_go", simplified: "去", traditional: "去", pinyin: "qù", tones: [4], english: "to go", partOfSpeech: "verb", hskLevel: 1, category: "Travel" },
  { id: "wd_come", simplified: "来", traditional: "來", pinyin: "lái", tones: [2], english: "to come", partOfSpeech: "verb", hskLevel: 1, category: "Travel" },
  { id: "wd_walk", simplified: "走", traditional: "走", pinyin: "zǒu", tones: [3], english: "to walk", partOfSpeech: "verb", hskLevel: 1, category: "Travel" },
  { id: "wd_drive", simplified: "开车", traditional: "開車", pinyin: "kāi chē", tones: [1,1], english: "to drive", partOfSpeech: "verb", hskLevel: 2, category: "Transportation" },
  { id: "wd_bus", simplified: "公共汽车", traditional: "公共汽車", pinyin: "gōng gòng qì chē", tones: [1,4,4,1], english: "bus", partOfSpeech: "noun", hskLevel: 1, category: "Transportation" },
  { id: "wd_car", simplified: "车", traditional: "車", pinyin: "chē", tones: [1], english: "car", partOfSpeech: "noun", hskLevel: 1, category: "Transportation" },
  { id: "wd_airplane", simplified: "飞机", traditional: "飛機", pinyin: "fēi jī", tones: [1,1], english: "airplane", partOfSpeech: "noun", hskLevel: 1, category: "Transportation" },
  { id: "wd_taxi", simplified: "出租车", traditional: "出租車", pinyin: "chū zū chē", tones: [1,1,1], english: "taxi", partOfSpeech: "noun", hskLevel: 1, category: "Transportation" },
  { id: "wd_airport", simplified: "机场", traditional: "機場", pinyin: "jī chǎng", tones: [1,3], english: "airport", partOfSpeech: "noun", hskLevel: 2, category: "Transportation" },
  { id: "wd_station", simplified: "站", traditional: "站", pinyin: "zhàn", tones: [4], english: "station / stop", partOfSpeech: "noun", hskLevel: 2, category: "Transportation" },
  { id: "wd_home", simplified: "家", traditional: "家", pinyin: "jiā", tones: [1], english: "home / family", partOfSpeech: "noun", hskLevel: 1, category: "General" },
  { id: "wd_school", simplified: "学校", traditional: "學校", pinyin: "xue xiào", tones: [2,4], english: "school", partOfSpeech: "noun", hskLevel: 1, category: "School" },
  { id: "wd_hospital", simplified: "医院", traditional: "醫院", pinyin: "yī yuàn", tones: [1,4], english: "hospital", partOfSpeech: "noun", hskLevel: 1, category: "Health" },
  { id: "wd_restaurant", simplified: "饭馆", traditional: "飯館", pinyin: "fàn guǎn", tones: [4,3], english: "restaurant", partOfSpeech: "noun", hskLevel: 1, category: "Food" },
  { id: "wd_shop", simplified: "商店", traditional: "商店", pinyin: "shāng diàn", tones: [1,4], english: "shop", partOfSpeech: "noun", hskLevel: 1, category: "Shopping" },
  { id: "wd_hotel", simplified: "酒店", traditional: "酒店", pinyin: "jiǔ diàn", tones: [3,4], english: "hotel", partOfSpeech: "noun", hskLevel: 2, category: "Travel" },

  { id: "wd_big", simplified: "大", traditional: "大", pinyin: "dà", tones: [4], english: "big", partOfSpeech: "adjective", hskLevel: 1, category: "General" },
  { id: "wd_small", simplified: "小", traditional: "小", pinyin: "xiǎo", tones: [3], english: "small", partOfSpeech: "adjective", hskLevel: 1, category: "General" },
  { id: "wd_good", simplified: "好", traditional: "好", pinyin: "hǎo", tones: [3], english: "good", partOfSpeech: "adjective", hskLevel: 1, category: "General" },
  { id: "wd_bad", simplified: "坏", traditional: "壞", pinyin: "huài", tones: [4], english: "bad / broken", partOfSpeech: "adjective", hskLevel: 2, category: "General" },
  { id: "wd_hot", simplified: "热", traditional: "熱", pinyin: "rè", tones: [4], english: "hot", partOfSpeech: "adjective", hskLevel: 1, category: "Weather" },
  { id: "wd_cold", simplified: "冷", traditional: "冷", pinyin: "lěng", tones: [3], english: "cold", partOfSpeech: "adjective", hskLevel: 1, category: "Weather" },
  { id: "wd_fast", simplified: "快", traditional: "快", pinyin: "kuài", tones: [4], english: "fast", partOfSpeech: "adjective", hskLevel: 2, category: "General" },
  { id: "wd_slow", simplified: "慢", traditional: "慢", pinyin: "màn", tones: [4], english: "slow", partOfSpeech: "adjective", hskLevel: 2, category: "General" },
  { id: "wd_many", simplified: "多", traditional: "多", pinyin: "duō", tones: [1], english: "many / much", partOfSpeech: "adjective", hskLevel: 1, category: "General" },
  { id: "wd_few", simplified: "少", traditional: "少", pinyin: "shǎo", tones: [3], english: "few / little", partOfSpeech: "adjective", hskLevel: 1, category: "General" },
  { id: "wd_expensive", simplified: "贵", traditional: "貴", pinyin: "guì", tones: [4], english: "expensive", partOfSpeech: "adjective", hskLevel: 2, category: "Shopping" },
  { id: "wd_cheap", simplified: "便宜", traditional: "便宜", pinyin: "pián yi", tones: [2,5], english: "cheap", partOfSpeech: "adjective", hskLevel: 2, category: "Shopping" },
  { id: "wd_beautiful", simplified: "漂亮", traditional: "漂亮", pinyin: "piào liang", tones: [4,5], english: "pretty", partOfSpeech: "adjective", hskLevel: 1, category: "General" },
  { id: "wd_happy", simplified: "高兴", traditional: "高興", pinyin: "gāo xìng", tones: [1,4], english: "happy", partOfSpeech: "adjective", hskLevel: 1, category: "Emotions" },
  { id: "wd_tired", simplified: "累", traditional: "累", pinyin: "lèi", tones: [4], english: "tired", partOfSpeech: "adjective", hskLevel: 2, category: "Emotions" },

  { id: "wd_see", simplified: "看", traditional: "看", pinyin: "kàn", tones: [4], english: "to look / watch", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_listen", simplified: "听", traditional: "聽", pinyin: "tīng", tones: [1], english: "to listen", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_speak", simplified: "说", traditional: "說", pinyin: "shuō", tones: [1], english: "to speak", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_read", simplified: "读", traditional: "讀", pinyin: "dú", tones: [2], english: "to read", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_write", simplified: "写", traditional: "寫", pinyin: "xiě", tones: [3], english: "to write", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_ask", simplified: "问", traditional: "問", pinyin: "wèn", tones: [4], english: "to ask", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_answer", simplified: "回答", traditional: "回答", pinyin: "huí dá", tones: [2,2], english: "to answer", partOfSpeech: "verb", hskLevel: 2, category: "General" },
  { id: "wd_know", simplified: "知道", traditional: "知道", pinyin: "zhī dào", tones: [1,4], english: "to know", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_understand", simplified: "懂", traditional: "懂", pinyin: "dǒng", tones: [3], english: "to understand", partOfSpeech: "verb", hskLevel: 2, category: "General" },
  { id: "wd_think", simplified: "想", traditional: "想", pinyin: "xiǎng", tones: [3], english: "to think / want", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_like", simplified: "喜欢", traditional: "喜歡", pinyin: "xǐ huān", tones: [3,1], english: "to like", partOfSpeech: "verb", hskLevel: 1, category: "Emotions" },
  { id: "wd_love", simplified: "爱", traditional: "愛", pinyin: "ài", tones: [4], english: "to love", partOfSpeech: "verb", hskLevel: 1, category: "Emotions" },
  { id: "wd_want", simplified: "要", traditional: "要", pinyin: "yào", tones: [4], english: "to want / need", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_have", simplified: "有", traditional: "有", pinyin: "yǒu", tones: [3], english: "to have", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_buy", simplified: "买", traditional: "買", pinyin: "mǎi", tones: [3], english: "to buy", partOfSpeech: "verb", hskLevel: 1, category: "Shopping" },
  { id: "wd_sell", simplified: "卖", traditional: "賣", pinyin: "mài", tones: [4], english: "to sell", partOfSpeech: "verb", hskLevel: 2, category: "Shopping" },

  { id: "wd_money", simplified: "钱", traditional: "錢", pinyin: "qián", tones: [2], english: "money", partOfSpeech: "noun", hskLevel: 1, category: "Shopping" },
  { id: "wd_how_much", simplified: "多少", traditional: "多少", pinyin: "duō shǎo", tones: [1,3], english: "how much / how many", partOfSpeech: "pronoun", hskLevel: 1, category: "Shopping" },
  { id: "wd_yuan", simplified: "元", traditional: "元", pinyin: "yuán", tones: [2], english: "yuan", partOfSpeech: "measure", hskLevel: 1, category: "Shopping" },
  { id: "wd_kuai", simplified: "块", traditional: "塊", pinyin: "kuài", tones: [4], english: "kuai (colloquial yuan)", partOfSpeech: "measure", hskLevel: 1, category: "Shopping" },

  { id: "wd_name", simplified: "名字", traditional: "名字", pinyin: "míng zi", tones: [2,5], english: "name", partOfSpeech: "noun", hskLevel: 1, category: "General" },
  { id: "wd_called", simplified: "叫", traditional: "叫", pinyin: "jiào", tones: [4], english: "to be called", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_country", simplified: "国家", traditional: "國家", pinyin: "guó jiā", tones: [2,1], english: "country", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_china", simplified: "中国", traditional: "中國", pinyin: "zhōng guó", tones: [1,2], english: "China", partOfSpeech: "noun", hskLevel: 1, category: "General" },
  { id: "wd_person", simplified: "人", traditional: "人", pinyin: "rén", tones: [2], english: "person", partOfSpeech: "noun", hskLevel: 1, category: "General" },
  { id: "wd_language", simplified: "语言", traditional: "語言", pinyin: "yǔ yán", tones: [3,2], english: "language", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_chinese", simplified: "中文", traditional: "中文", pinyin: "zhōng wén", tones: [1,2], english: "Chinese (language)", partOfSpeech: "noun", hskLevel: 1, category: "General" },
  { id: "wd_english", simplified: "英文", traditional: "英文", pinyin: "yīng wén", tones: [1,2], english: "English (language)", partOfSpeech: "noun", hskLevel: 2, category: "General" },

  { id: "wd_where", simplified: "哪里", traditional: "哪裡", pinyin: "nǎ lǐ", tones: [3,3], english: "where", partOfSpeech: "pronoun", hskLevel: 1, category: "Directions" },
  { id: "wd_what", simplified: "什么", traditional: "什麼", pinyin: "shén me", tones: [2,5], english: "what", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_who", simplified: "谁", traditional: "誰", pinyin: "shéi", tones: [2], english: "who", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_when", simplified: "什么时候", traditional: "什麼時候", pinyin: "shén me shí hou", tones: [2,5,2,5], english: "when", partOfSpeech: "pronoun", hskLevel: 2, category: "Time" },
  { id: "wd_how", simplified: "怎么", traditional: "怎麼", pinyin: "zěn me", tones: [3,5], english: "how", partOfSpeech: "pronoun", hskLevel: 1, category: "General" },
  { id: "wd_why", simplified: "为什么", traditional: "為什麼", pinyin: "wèi shén me", tones: [4,2,5], english: "why", partOfSpeech: "pronoun", hskLevel: 2, category: "General" },

  { id: "wd_left", simplified: "左", traditional: "左", pinyin: "zuǒ", tones: [3], english: "left", partOfSpeech: "noun", hskLevel: 2, category: "Directions" },
  { id: "wd_right", simplified: "右", traditional: "右", pinyin: "yòu", tones: [4], english: "right", partOfSpeech: "noun", hskLevel: 2, category: "Directions" },
  { id: "wd_above", simplified: "上", traditional: "上", pinyin: "shàng", tones: [4], english: "up / above", partOfSpeech: "noun", hskLevel: 1, category: "Directions" },
  { id: "wd_below", simplified: "下", traditional: "下", pinyin: "xià", tones: [4], english: "down / below", partOfSpeech: "noun", hskLevel: 1, category: "Directions" },
  { id: "wd_front", simplified: "前", traditional: "前", pinyin: "qián", tones: [2], english: "front", partOfSpeech: "noun", hskLevel: 2, category: "Directions" },
  { id: "wd_back", simplified: "后", traditional: "後", pinyin: "hòu", tones: [4], english: "behind", partOfSpeech: "noun", hskLevel: 2, category: "Directions" },
  { id: "wd_inside", simplified: "里", traditional: "裡", pinyin: "lǐ", tones: [3], english: "inside", partOfSpeech: "noun", hskLevel: 1, category: "Directions" },
  { id: "wd_outside", simplified: "外", traditional: "外", pinyin: "wài", tones: [4], english: "outside", partOfSpeech: "noun", hskLevel: 2, category: "Directions" },
  { id: "wd_near", simplified: "近", traditional: "近", pinyin: "jìn", tones: [4], english: "near", partOfSpeech: "adjective", hskLevel: 2, category: "Directions" },
  { id: "wd_far", simplified: "远", traditional: "遠", pinyin: "yuǎn", tones: [3], english: "far", partOfSpeech: "adjective", hskLevel: 2, category: "Directions" },

  { id: "wd_red", simplified: "红", traditional: "紅", pinyin: "hóng", tones: [2], english: "red", partOfSpeech: "adjective", hskLevel: 2, category: "Colors" },
  { id: "wd_blue", simplified: "蓝", traditional: "藍", pinyin: "lán", tones: [2], english: "blue", partOfSpeech: "adjective", hskLevel: 3, category: "Colors" },
  { id: "wd_green", simplified: "绿", traditional: "綠", pinyin: "lǜ", tones: [4], english: "green", partOfSpeech: "adjective", hskLevel: 3, category: "Colors" },
  { id: "wd_yellow", simplified: "黄", traditional: "黃", pinyin: "huáng", tones: [2], english: "yellow", partOfSpeech: "adjective", hskLevel: 3, category: "Colors" },
  { id: "wd_white", simplified: "白", traditional: "白", pinyin: "bái", tones: [2], english: "white", partOfSpeech: "adjective", hskLevel: 2, category: "Colors" },
  { id: "wd_black", simplified: "黑", traditional: "黑", pinyin: "hēi", tones: [1], english: "black", partOfSpeech: "adjective", hskLevel: 2, category: "Colors" },
  { id: "wd_very", simplified: "很", traditional: "很", pinyin: "hěn", tones: [3], english: "very", partOfSpeech: "adverb", hskLevel: 1, category: "General" },
  { id: "wd_too", simplified: "太", traditional: "太", pinyin: "tài", tones: [4], english: "too (much)", partOfSpeech: "adverb", hskLevel: 1, category: "General" },
  { id: "wd_also", simplified: "也", traditional: "也", pinyin: "yě", tones: [3], english: "also", partOfSpeech: "adverb", hskLevel: 1, category: "General" },
  { id: "wd_all", simplified: "都", traditional: "都", pinyin: "dōu", tones: [1], english: "all / both", partOfSpeech: "adverb", hskLevel: 1, category: "General" },
  { id: "wd_can", simplified: "能", traditional: "能", pinyin: "néng", tones: [2], english: "can / able", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_may", simplified: "可以", traditional: "可以", pinyin: "kě yǐ", tones: [3,3], english: "may / can", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_learn", simplified: "学习", traditional: "學習", pinyin: "xué xí", tones: [2,2], english: "to study", partOfSpeech: "verb", hskLevel: 1, category: "School" },
  { id: "wd_work", simplified: "工作", traditional: "工作", pinyin: "gōng zuò", tones: [1,4], english: "to work / job", partOfSpeech: "verb", hskLevel: 1, category: "Business" },
  { id: "wd_rest", simplified: "休息", traditional: "休息", pinyin: "xiū xi", tones: [1,5], english: "to rest", partOfSpeech: "verb", hskLevel: 2, category: "General" },
  { id: "wd_sleep", simplified: "睡觉", traditional: "睡覺", pinyin: "shuì jiào", tones: [4,4], english: "to sleep", partOfSpeech: "verb", hskLevel: 1, category: "General" },
  { id: "wd_play", simplified: "玩", traditional: "玩", pinyin: "wán", tones: [2], english: "to play", partOfSpeech: "verb", hskLevel: 2, category: "Hobbies" },

  // HSK 2 (60 words)
  { id: "wd_meeting", simplified: "会议", traditional: "會議", pinyin: "huì yì", tones: [4,4], english: "meeting", partOfSpeech: "noun", hskLevel: 2, category: "Business" },
  { id: "wd_schedule", simplified: "日程", traditional: "日程", pinyin: "rì chéng", tones: [4,2], english: "schedule", partOfSpeech: "noun", hskLevel: 2, category: "Business" },
  { id: "wd_contract", simplified: "合同", traditional: "合同", pinyin: "hé tóng", tones: [2,2], english: "contract", partOfSpeech: "noun", hskLevel: 2, category: "Business" },
  { id: "wd_room", simplified: "房间", traditional: "房間", pinyin: "fáng jiān", tones: [2,1], english: "room", partOfSpeech: "noun", hskLevel: 2, category: "Travel" },
  { id: "wd_breakfast", simplified: "早餐", traditional: "早餐", pinyin: "zǎo cān", tones: [3,1], english: "breakfast", partOfSpeech: "noun", hskLevel: 2, category: "Food" },
  { id: "wd_lunch", simplified: "午餐", traditional: "午餐", pinyin: "wǔ cān", tones: [3,1], english: "lunch", partOfSpeech: "noun", hskLevel: 2, category: "Food" },
  { id: "wd_dinner", simplified: "晚餐", traditional: "晚餐", pinyin: "wǎn cān", tones: [3,1], english: "dinner", partOfSpeech: "noun", hskLevel: 2, category: "Food" },
  { id: "wd_key", simplified: "钥匙", traditional: "鑰匙", pinyin: "yào shi", tones: [4,5], english: "key", partOfSpeech: "noun", hskLevel: 2, category: "Travel" },
  { id: "wd_stop", simplified: "停", traditional: "停", pinyin: "tíng", tones: [2], english: "to stop", partOfSpeech: "verb", hskLevel: 2, category: "Transportation" },
  { id: "wd_left_turn", simplified: "左转", traditional: "左轉", pinyin: "zuǒ zhuǎn", tones: [3,3], english: "turn left", partOfSpeech: "phrase", hskLevel: 2, category: "Directions" },
  { id: "wd_right_turn", simplified: "右转", traditional: "右轉", pinyin: "yòu zhuǎn", tones: [4,3], english: "turn right", partOfSpeech: "phrase", hskLevel: 2, category: "Directions" },
  { id: "wd_straight", simplified: "直走", traditional: "直走", pinyin: "zhí zǒu", tones: [2,3], english: "go straight", partOfSpeech: "phrase", hskLevel: 2, category: "Directions" },
  { id: "wd_subway", simplified: "地铁", traditional: "地鐵", pinyin: "dì tiě", tones: [4,3], english: "subway", partOfSpeech: "noun", hskLevel: 2, category: "Transportation" },
  { id: "wd_train", simplified: "火车", traditional: "火車", pinyin: "huǒ chē", tones: [3,1], english: "train", partOfSpeech: "noun", hskLevel: 2, category: "Transportation" },
  { id: "wd_bicycle", simplified: "自行车", traditional: "自行車", pinyin: "zì xíng chē", tones: [4,2,1], english: "bicycle", partOfSpeech: "noun", hskLevel: 2, category: "Transportation" },
  { id: "wd_ticket", simplified: "票", traditional: "票", pinyin: "piào", tones: [4], english: "ticket", partOfSpeech: "noun", hskLevel: 2, category: "Travel" },
  { id: "wd_passport", simplified: "护照", traditional: "護照", pinyin: "hù zhào", tones: [4,4], english: "passport", partOfSpeech: "noun", hskLevel: 2, category: "Travel" },
  { id: "wd_map", simplified: "地图", traditional: "地圖", pinyin: "dì tú", tones: [4,2], english: "map", partOfSpeech: "noun", hskLevel: 2, category: "Travel" },
  { id: "wd_phone", simplified: "电话", traditional: "電話", pinyin: "diàn huà", tones: [4,4], english: "phone", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_computer", simplified: "电脑", traditional: "電腦", pinyin: "diàn nǎo", tones: [4,3], english: "computer", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_internet", simplified: "互联网", traditional: "互聯網", pinyin: "hù lián wǎng", tones: [4,2,3], english: "internet", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_email", simplified: "电子邮件", traditional: "電子郵件", pinyin: "diàn zǐ yóu jiàn", tones: [4,3,2,4], english: "email", partOfSpeech: "noun", hskLevel: 2, category: "Business" },
  { id: "wd_wifi", simplified: "无线网", traditional: "無線網", pinyin: "wú xiàn wǎng", tones: [2,4,3], english: "wifi", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_music", simplified: "音乐", traditional: "音樂", pinyin: "yīn yuè", tones: [1,4], english: "music", partOfSpeech: "noun", hskLevel: 2, category: "Hobbies" },
  { id: "wd_song", simplified: "歌", traditional: "歌", pinyin: "gē", tones: [1], english: "song", partOfSpeech: "noun", hskLevel: 2, category: "Hobbies" },
  { id: "wd_movie", simplified: "电影", traditional: "電影", pinyin: "diàn yǐng", tones: [4,3], english: "movie", partOfSpeech: "noun", hskLevel: 2, category: "Hobbies" },
  { id: "wd_book", simplified: "书", traditional: "書", pinyin: "shū", tones: [1], english: "book", partOfSpeech: "noun", hskLevel: 2, category: "School" },
  { id: "wd_newspaper", simplified: "报纸", traditional: "報紙", pinyin: "bào zhǐ", tones: [4,3], english: "newspaper", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_question", simplified: "问题", traditional: "問題", pinyin: "wèn tí", tones: [4,2], english: "question / problem", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_answer2", simplified: "答案", traditional: "答案", pinyin: "dá àn", tones: [2,4], english: "answer", partOfSpeech: "noun", hskLevel: 2, category: "General" },
  { id: "wd_weather", simplified: "天气", traditional: "天氣", pinyin: "tiān qì", tones: [1,4], english: "weather", partOfSpeech: "noun", hskLevel: 2, category: "Weather" },
  { id: "wd_sun", simplified: "太阳", traditional: "太陽", pinyin: "tài yáng", tones: [4,2], english: "sun", partOfSpeech: "noun", hskLevel: 2, category: "Weather" },
  { id: "wd_rain", simplified: "雨", traditional: "雨", pinyin: "yǔ", tones: [3], english: "rain", partOfSpeech: "noun", hskLevel: 2, category: "Weather" },
  { id: "wd_snow", simplified: "雪", traditional: "雪", pinyin: "xuě", tones: [3], english: "snow", partOfSpeech: "noun", hskLevel: 2, category: "Weather" },
  { id: "wd_wind", simplified: "风", traditional: "風", pinyin: "fēng", tones: [1], english: "wind", partOfSpeech: "noun", hskLevel: 2, category: "Weather" },
  { id: "wd_happy2", simplified: "开心", traditional: "開心", pinyin: "kāi xīn", tones: [1,1], english: "happy", partOfSpeech: "adjective", hskLevel: 2, category: "Emotions" },
  { id: "wd_sad", simplified: "伤心", traditional: "傷心", pinyin: "shāng xīn", tones: [1,1], english: "sad", partOfSpeech: "adjective", hskLevel: 2, category: "Emotions" },
  { id: "wd_angry", simplified: "生气", traditional: "生氣", pinyin: "shēng qì", tones: [1,4], english: "angry", partOfSpeech: "adjective", hskLevel: 2, category: "Emotions" },
  { id: "wd_scared", simplified: "害怕", traditional: "害怕", pinyin: "hài pà", tones: [4,4], english: "afraid", partOfSpeech: "adjective", hskLevel: 2, category: "Emotions" },
  { id: "wd_busy", simplified: "忙", traditional: "忙", pinyin: "máng", tones: [2], english: "busy", partOfSpeech: "adjective", hskLevel: 2, category: "Emotions" },
  { id: "wd_hungry", simplified: "饿", traditional: "餓", pinyin: "è", tones: [4], english: "hungry", partOfSpeech: "adjective", hskLevel: 2, category: "Food" },
  { id: "wd_thirsty", simplified: "渴", traditional: "渴", pinyin: "kě", tones: [3], english: "thirsty", partOfSpeech: "adjective", hskLevel: 2, category: "Food" },
  { id: "wd_sick", simplified: "生病", traditional: "生病", pinyin: "shēng bìng", tones: [1,4], english: "sick", partOfSpeech: "adjective", hskLevel: 2, category: "Health" },
  { id: "wd_pain", simplified: "疼", traditional: "疼", pinyin: "téng", tones: [2], english: "painful", partOfSpeech: "adjective", hskLevel: 2, category: "Health" },
  { id: "wd_medicine", simplified: "药", traditional: "藥", pinyin: "yào", tones: [4], english: "medicine", partOfSpeech: "noun", hskLevel: 2, category: "Health" },
  { id: "wd_head", simplified: "头", traditional: "頭", pinyin: "tóu", tones: [2], english: "head", partOfSpeech: "noun", hskLevel: 2, category: "Body" },
  { id: "wd_eye", simplified: "眼睛", traditional: "眼睛", pinyin: "yǎn jīng", tones: [3,1], english: "eye", partOfSpeech: "noun", hskLevel: 2, category: "Body" },
  { id: "wd_hand", simplified: "手", traditional: "手", pinyin: "shǒu", tones: [3], english: "hand", partOfSpeech: "noun", hskLevel: 2, category: "Body" },
  { id: "wd_foot", simplified: "脚", traditional: "腳", pinyin: "jiǎo", tones: [3], english: "foot", partOfSpeech: "noun", hskLevel: 2, category: "Body" },
  { id: "wd_heart", simplified: "心", traditional: "心", pinyin: "xīn", tones: [1], english: "heart", partOfSpeech: "noun", hskLevel: 2, category: "Body" },
  { id: "wd_dog", simplified: "狗", traditional: "狗", pinyin: "gǒu", tones: [3], english: "dog", partOfSpeech: "noun", hskLevel: 2, category: "Animals" },
  { id: "wd_cat", simplified: "猫", traditional: "貓", pinyin: "māo", tones: [1], english: "cat", partOfSpeech: "noun", hskLevel: 2, category: "Animals" },
  { id: "wd_bird", simplified: "鸟", traditional: "鳥", pinyin: "niǎo", tones: [3], english: "bird", partOfSpeech: "noun", hskLevel: 2, category: "Animals" },
  { id: "wd_panda", simplified: "熊猫", traditional: "熊貓", pinyin: "xióng māo", tones: [2,1], english: "panda", partOfSpeech: "noun", hskLevel: 2, category: "Animals" },
  { id: "wd_flower", simplified: "花", traditional: "花", pinyin: "huā", tones: [1], english: "flower", partOfSpeech: "noun", hskLevel: 2, category: "Nature" },
  { id: "wd_tree", simplified: "树", traditional: "樹", pinyin: "shù", tones: [4], english: "tree/wood", partOfSpeech: "noun", hskLevel: 2, category: "Nature" },
  { id: "wd_mountain", simplified: "山", traditional: "山", pinyin: "shān", tones: [1], english: "mountain", partOfSpeech: "noun", hskLevel: 2, category: "Nature" },
  { id: "wd_river", simplified: "河", traditional: "河", pinyin: "hé", tones: [2], english: "river", partOfSpeech: "noun", hskLevel: 2, category: "Nature" },
  { id: "wd_sea", simplified: "海", traditional: "海", pinyin: "hǎi", tones: [3], english: "sea", partOfSpeech: "noun", hskLevel: 2, category: "Nature" },
  { id: "wd_city", simplified: "城市", traditional: "城市", pinyin: "chéng shì", tones: [2,4], english: "city", partOfSpeech: "noun", hskLevel: 2, category: "General" },

  // HSK 3 (40 words)
  { id: "wd_experience", simplified: "经验", traditional: "經驗", pinyin: "jīng yàn", tones: [1,4], english: "experience", partOfSpeech: "noun", hskLevel: 3, category: "Business" },
  { id: "wd_opportunity", simplified: "机会", traditional: "機會", pinyin: "jī huì", tones: [1,4], english: "opportunity", partOfSpeech: "noun", hskLevel: 3, category: "Business" },
  { id: "wd_environment", simplified: "环境", traditional: "環境", pinyin: "huán jìng", tones: [2,4], english: "environment", partOfSpeech: "noun", hskLevel: 3, category: "Nature" },
  { id: "wd_economy", simplified: "经济", traditional: "經濟", pinyin: "jīng jì", tones: [1,4], english: "economy", partOfSpeech: "noun", hskLevel: 3, category: "Business" },
  { id: "wd_culture", simplified: "文化", traditional: "文化", pinyin: "wén huà", tones: [2,4], english: "culture", partOfSpeech: "noun", hskLevel: 3, category: "General" },
  { id: "wd_history", simplified: "历史", traditional: "歷史", pinyin: "lì shǐ", tones: [4,3], english: "history", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_future", simplified: "未来", traditional: "未來", pinyin: "wèi lái", tones: [4,2], english: "future", partOfSpeech: "noun", hskLevel: 3, category: "Time" },
  { id: "wd_memory", simplified: "记忆", traditional: "記憶", pinyin: "jì yì", tones: [4,4], english: "memory", partOfSpeech: "noun", hskLevel: 3, category: "General" },
  { id: "wd_opinion", simplified: "意见", traditional: "意見", pinyin: "yì jiàn", tones: [4,4], english: "opinion", partOfSpeech: "noun", hskLevel: 3, category: "General" },
  { id: "wd_important", simplified: "重要", traditional: "重要", pinyin: "zhòng yào", tones: [4,4], english: "important", partOfSpeech: "adjective", hskLevel: 3, category: "General" },
  { id: "wd_difficult", simplified: "难", traditional: "難", pinyin: "nán", tones: [2], english: "difficult", partOfSpeech: "adjective", hskLevel: 3, category: "General" },
  { id: "wd_easy", simplified: "容易", traditional: "容易", pinyin: "róng yì", tones: [2,4], english: "easy", partOfSpeech: "adjective", hskLevel: 3, category: "General" },
  { id: "wd_interesting", simplified: "有意思", traditional: "有意思", pinyin: "yǒu yì si", tones: [3,4,5], english: "interesting", partOfSpeech: "adjective", hskLevel: 3, category: "Emotions" },
  { id: "wd_boring", simplified: "无聊", traditional: "無聊", pinyin: "wú liáo", tones: [2,2], english: "boring", partOfSpeech: "adjective", hskLevel: 3, category: "Emotions" },
  { id: "wd_convenient", simplified: "方便", traditional: "方便", pinyin: "fāng biàn", tones: [1,4], english: "convenient", partOfSpeech: "adjective", hskLevel: 3, category: "General" },
  { id: "wd_clean", simplified: "干净", traditional: "乾淨", pinyin: "gān jìng", tones: [1,4], english: "clean", partOfSpeech: "adjective", hskLevel: 3, category: "General" },
  { id: "wd_dirty", simplified: "脏", traditional: "髒", pinyin: "zāng", tones: [1], english: "dirty", partOfSpeech: "adjective", hskLevel: 3, category: "General" },
  { id: "wd_safe", simplified: "安全", traditional: "安全", pinyin: "ān quán", tones: [1,2], english: "safe", partOfSpeech: "adjective", hskLevel: 3, category: "General" },
  { id: "wd_dangerous", simplified: "危险", traditional: "危險", pinyin: "wēi xiǎn", tones: [1,3], english: "dangerous", partOfSpeech: "adjective", hskLevel: 3, category: "General" },
  { id: "wd_help", simplified: "帮助", traditional: "幫助", pinyin: "bāng zhù", tones: [1,4], english: "to help", partOfSpeech: "verb", hskLevel: 3, category: "General" },
  { id: "wd_change", simplified: "改变", traditional: "改變", pinyin: "gǎi biàn", tones: [3,4], english: "to change", partOfSpeech: "verb", hskLevel: 3, category: "General" },
  { id: "wd_develop", simplified: "发展", traditional: "發展", pinyin: "fā zhǎn", tones: [1,3], english: "to develop", partOfSpeech: "verb", hskLevel: 3, category: "Business" },
  { id: "wd_introduce", simplified: "介绍", traditional: "介紹", pinyin: "jiè shào", tones: [4,4], english: "to introduce", partOfSpeech: "verb", hskLevel: 3, category: "General" },
  { id: "wd_use", simplified: "用", traditional: "用", pinyin: "yòng", tones: [4], english: "to use", partOfSpeech: "verb", hskLevel: 3, category: "General" },
  { id: "wd_forget", simplified: "忘记", traditional: "忘記", pinyin: "wàng jì", tones: [4,4], english: "to forget", partOfSpeech: "verb", hskLevel: 3, category: "General" },
  { id: "wd_remember", simplified: "记住", traditional: "記住", pinyin: "jì zhù", tones: [4,4], english: "to remember", partOfSpeech: "verb", hskLevel: 3, category: "General" },
  { id: "wd_decide", simplified: "决定", traditional: "決定", pinyin: "jué dìng", tones: [2,4], english: "to decide", partOfSpeech: "verb", hskLevel: 3, category: "General" },
  { id: "wd_suggest", simplified: "建议", traditional: "建議", pinyin: "jiàn yì", tones: [4,4], english: "to suggest", partOfSpeech: "verb", hskLevel: 3, category: "Business" },
  { id: "wd_practice", simplified: "练习", traditional: "練習", pinyin: "liàn xí", tones: [4,2], english: "to practice", partOfSpeech: "verb", hskLevel: 3, category: "School" },
  { id: "wd_exam", simplified: "考试", traditional: "考試", pinyin: "kǎo shì", tones: [3,4], english: "exam", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_study", simplified: "学习", traditional: "學習", pinyin: "xué xí", tones: [2,2], english: "to study", partOfSpeech: "verb", hskLevel: 3, category: "School" },
  { id: "wd_lesson", simplified: "课", traditional: "課", pinyin: "kè", tones: [4], english: "class / lesson", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_university", simplified: "大学", traditional: "大學", pinyin: "dà xué", tones: [4,2], english: "university", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_library", simplified: "图书馆", traditional: "圖書館", pinyin: "tú shū guǎn", tones: [2,1,3], english: "library", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_class", simplified: "班", traditional: "班", pinyin: "bān", tones: [1], english: "class", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_homework", simplified: "作业", traditional: "作業", pinyin: "zuò yè", tones: [4,4], english: "homework", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_dictionary", simplified: "字典", traditional: "字典", pinyin: "zì diǎn", tones: [4,3], english: "dictionary", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_grammar", simplified: "语法", traditional: "語法", pinyin: "yǔ fǎ", tones: [3,3], english: "grammar", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_character", simplified: "字", traditional: "字", pinyin: "zì", tones: [4], english: "character", partOfSpeech: "noun", hskLevel: 3, category: "School" },
  { id: "wd_pronunciation", simplified: "发音", traditional: "發音", pinyin: "fā yīn", tones: [1,1], english: "pronunciation", partOfSpeech: "noun", hskLevel: 3, category: "School" }
];
